Repository go-acme/lego, pull requests merged in 2018-09, with the labels that each got.

#607 Submit all dns records up front, then validate serially
  acme/client.go
  acme/dns_challenge.go
Labels: area/lib

#606 Add DNS Provider for IIJ
  Gopkg.lock
  cli.go
  providers/dns/dns_providers.go
  providers/dns/iij/iij.go
  providers/dns/iij/iij_test.go
  vendor/github.com/iij/doapi/api.go
  vendor/github.com/iij/doapi/parse.go
  vendor/github.com/iij/doapi/protocol/Commit.go
  vendor/github.com/iij/doapi/protocol/RecordAdd.go
  vendor/github.com/iij/doapi/protocol/RecordDelete.go
  vendor/github.com/iij/doapi/protocol/RecordGet.go
  vendor/github.com/iij/doapi/protocol/RecordListGet.go
  vendor/github.com/iij/doapi/protocol/Reset.go
  vendor/github.com/iij/doapi/protocol/ZoneListGet.go
  vendor/github.com/iij/doapi/protocol/common.go
Labels: area/dnsprovider

#603 Route53: Make it possible to configure from the env
  platform/config/env/env.go
  platform/config/env/env_test.go
  providers/dns/route53/route53.go
  providers/dns/route53/route53_integration_test.go
  providers/dns/route53/route53_test.go
Labels: area/dnsprovider

#610 Add DNS Provider for netcup
  cli.go
  providers/dns/dns_providers.go
  providers/dns/netcup/client.go
  providers/dns/netcup/client_test.go
  providers/dns/netcup/netcup.go
  providers/dns/netcup/netcup_test.go
Labels: area/dnsprovider

#612 Add filename parameter
  cli.go
  cli_handlers.go
Labels: area/cli

#627 Panic on generating a certificate
  acme/client.go
Labels: area/lib, bug

#631 Check error to avoid panic due to nil client
  providers/dns/ovh/ovh.go
  providers/dns/route53/route53.go
  providers/dns/route53/route53_test.go
Labels: area/dnsprovider, bug

#635 Update iij version to remove CRLF
  Gopkg.lock
  vendor/github.com/iij/doapi/api.go
  vendor/github.com/iij/doapi/protocol/Commit.go
  vendor/github.com/iij/doapi/protocol/RecordAdd.go
  vendor/github.com/iij/doapi/protocol/RecordDelete.go
  vendor/github.com/iij/doapi/protocol/RecordGet.go
  vendor/github.com/iij/doapi/protocol/RecordListGet.go
  vendor/github.com/iij/doapi/protocol/Reset.go
  vendor/github.com/iij/doapi/protocol/ZoneListGet.go
Labels: area/dnsprovider

#636 Rename Alibaba DNS env var.
  cli.go
  providers/dns/alidns/alidns.go
  providers/dns/alidns/alidns_test.go
Labels: area/dnsprovider, bug

#630 Use Testify.
  acme/client_test.go
  acme/crypto_test.go
  acme/dns_challenge.go
  acme/dns_challenge_test.go
  acme/http_challenge_test.go
  acme/http_test.go
  acme/tls_alpn_challenge_test.go
Labels: area/lib

#629 CloudXNS: client isolation.
  providers/dns/cloudxns/client.go
  providers/dns/cloudxns/client_test.go
  providers/dns/cloudxns/cloudxns.go
Labels: area/dnsprovider, bug

#639 Use an interface for logger.
  log/logger.go
Labels: area/lib

#642 dns providers: fix errors.
  providers/dns/azure/azure.go
  providers/dns/gcloud/googlecloud.go
  providers/dns/iij/iij.go
Labels: area/dnsprovider, bug

#643 Fix: gcloud wildcard
  acme/client.go
  acme/dns_challenge.go
  providers/dns/gcloud/googlecloud.go
  providers/dns/gcloud/googlecloud_test.go
Labels: area/dnsprovider, bug

#640 ns1: fix getHostedZone.
  providers/dns/ns1/ns1.go
  providers/dns/ns1/ns1_test.go
Labels: area/dnsprovider, bug

#646 Correct example of renew action with days flag
  README.md
Labels: area/documentation
