Repository go-acme/lego, pull requests merged in 2018-12, with the labels that each got.

#726 Azure: Do not overwrite existing TXT records
  providers/dns/azure/azure.go
Labels: area/dnsprovider, bug

#728 Release helper
  Makefile
  acme/api/internal/sender/useragent.go
  internal/release.go
Labels: area/infrastructure, enhancement

#735 Use new challtestsrv.
  .travis.yml
  e2e/loader/loader.go
  e2e/readme.md
Labels: area/infrastructure, bug

#736 fix: errors management in the prober.
  challenge/resolver/prober.go
Labels: area/dnsprovider, bug

#739 alidns: add support to handle more than 20 domains
  providers/dns/alidns/alidns.go
Labels: area/dnsprovider, enhancement

#740 gcloud: fix for wildcard
  Gopkg.lock
  challenge/dns01/dns_challenge.go
  challenge/dns01/precheck.go
  e2e/loader/loader.go
  platform/wait/wait.go
  platform/wait/wait_test.go
  providers/dns/gcloud/googlecloud.go
  providers/dns/nifcloud/nifcloud.go
  providers/dns/route53/route53.go
Labels: area/dnsprovider, bug

#743 Removed an outdated instruction
  README.md
Labels: area/documentation, bug
