Repository go-acme/lego, pull requests merged in 2018-06, with the labels that each got.

#571 ACME HTTP: Allow customizing HTTP client x509.CertPool
  acme/http.go
  acme/http_test.go
Labels: area/cli

#565 Review DNS providers.
  platform/config/env/env.go
  providers/dns/auroradns/auroradns.go
  providers/dns/auroradns/auroradns_test.go
  providers/dns/azure/azure.go
  providers/dns/azure/azure_test.go
  providers/dns/bluecat/bluecat.go
  providers/dns/cloudflare/cloudflare.go
  providers/dns/cloudflare/cloudflare_test.go
  providers/dns/cloudxns/cloudxns.go
  providers/dns/cloudxns/cloudxns_test.go
  providers/dns/digitalocean/digitalocean.go
  providers/dns/digitalocean/digitalocean_test.go
  providers/dns/dns_providers_test.go
  providers/dns/dnsimple/dnsimple_test.go
  providers/dns/dnsmadeeasy/dnsmadeeasy.go
  providers/dns/dnspod/dnspod.go
  providers/dns/dnspod/dnspod_test.go
  providers/dns/duckdns/duckdns.go
  providers/dns/duckdns/duckdns_test.go
  providers/dns/dyn/dyn.go
  providers/dns/exoscale/exoscale.go
  providers/dns/exoscale/exoscale_test.go
  providers/dns/fastdns/fastdns.go
  providers/dns/fastdns/fastdns_test.go
  providers/dns/gandi/gandi.go
  providers/dns/gandi/gandi_test.go
  providers/dns/gandiv5/gandiv5.go
  providers/dns/gandiv5/gandiv5_test.go
  providers/dns/gcloud/googlecloud.go
  providers/dns/gcloud/googlecloud_test.go
  providers/dns/glesys/glesys.go
  providers/dns/godaddy/godaddy.go
  providers/dns/lightsail/lightsail_integration_test.go
  providers/dns/lightsail/lightsail_test.go
  providers/dns/linode/linode.go
  providers/dns/linode/linode_test.go
  providers/dns/namecheap/namecheap.go
  providers/dns/namecheap/namecheap_test.go
  providers/dns/namedotcom/namedotcom.go
  providers/dns/namedotcom/namedotcom_test.go
  providers/dns/ns1/ns1.go
  providers/dns/ns1/ns1_test.go
  providers/dns/otc/otc.go
  providers/dns/otc/otc_test.go
  providers/dns/ovh/ovh.go
  providers/dns/ovh/ovh_test.go
  providers/dns/pdns/pdns.go
  providers/dns/pdns/pdns_test.go
  providers/dns/rackspace/rackspace.go
  providers/dns/rfc2136/rfc2136.go
  providers/dns/rfc2136/rfc2136_test.go
  providers/dns/route53/route53_integration_test.go
  providers/dns/route53/route53_test.go
  providers/dns/vultr/vultr.go
  providers/dns/vultr/vultr_test.go
Labels: area/dnsprovider

#572 TLS-ALPN-01 Challenge
  README.md
  acme/challenges.go
  acme/client.go
  acme/client_test.go
  acme/crypto.go
  acme/crypto_test.go
  acme/tls_alpn_challenge.go
  acme/tls_alpn_challenge_server.go
  acme/tls_alpn_challenge_test.go
  cli.go
  cli_handlers.go
Labels: area/lib

#579 tls-alpn: add a function to return PEM blocks.
  acme/tls_alpn_challenge.go
  acme/tls_alpn_challenge_server.go
Labels: area/lib

#580 Review DNS providers
  acme/client.go
  acme/client_test.go
  acme/dns_challenge.go
  acme/dns_challenge_manual.go
  acme/http.go
  acme/http_challenge.go
  acme/http_challenge_server.go
  acme/http_test.go
  acme/tls_alpn_challenge.go
  log/logger.go
  providers/dns/auroradns/auroradns.go
  providers/dns/auroradns/auroradns_test.go
  providers/dns/azure/azure.go
  providers/dns/bluecat/bluecat.go
  providers/dns/cloudflare/cloudflare.go
  providers/dns/cloudxns/cloudxns.go
  providers/dns/digitalocean/digitalocean.go
  providers/dns/dns_providers.go
  providers/dns/dnsimple/dnsimple.go
  providers/dns/dnsmadeeasy/dnsmadeeasy.go
  providers/dns/dnspod/dnspod.go
  providers/dns/dyn/dyn.go
  providers/dns/exoscale/exoscale.go
  providers/dns/fastdns/fastdns.go
  providers/dns/gandi/gandi.go
  providers/dns/gandiv5/gandiv5.go
  providers/dns/gcloud/googlecloud.go
  providers/dns/glesys/glesys.go
  providers/dns/godaddy/godaddy.go
  providers/dns/lightsail/lightsail.go
  providers/dns/linode/linode.go
  providers/dns/linode/linode_test.go
  providers/dns/namecheap/namecheap.go
  providers/dns/namecheap/namecheap_test.go
  providers/dns/namedotcom/namedotcom.go
  providers/dns/ns1/ns1.go
  providers/dns/otc/mock.go
  providers/dns/otc/otc.go
  providers/dns/ovh/ovh.go
  providers/dns/pdns/pdns.go
  providers/dns/rackspace/rackspace.go
  providers/dns/vultr/vultr.go
Labels: area/dnsprovider

#581 Order polling wait
  acme/client.go
Labels: area/lib

#585 Replace Dial by DialContext.
  acme/http.go
Labels: area/lib

#589 Don't trust identifiers order.
  acme/client.go
  acme/crypto.go
Labels: area/lib, bug

#590 CA Server Name.
  acme/http.go
Labels: area/cli

#553 Add DNS Provider for VegaDNS
  Gopkg.lock
  cli.go
  providers/dns/dns_providers.go
  providers/dns/vegadns/vegadns.go
  providers/dns/vegadns/vegadns_test.go
  vendor/github.com/OpenDNS/vegadns2client/LICENSE
  vendor/github.com/OpenDNS/vegadns2client/client.go
  vendor/github.com/OpenDNS/vegadns2client/domains.go
  vendor/github.com/OpenDNS/vegadns2client/main.go
  vendor/github.com/OpenDNS/vegadns2client/records.go
  vendor/github.com/OpenDNS/vegadns2client/tokens.go
Labels: area/dnsprovider
