Repository go-acme/lego, pull requests merged in 2018-11, with the labels that each got.

#692 add ConoHa DNS provider
  CONTRIBUTING.md
  cli.go
  providers/dns/conoha/client.go
  providers/dns/conoha/client_test.go
  providers/dns/conoha/conoha.go
  providers/dns/conoha/conoha_test.go
  providers/dns/dns_providers.go
Labels: area/dnsprovider, enhancement

#697 conoha: fix finding domain id
  providers/dns/conoha/conoha.go
Labels: area/dnsprovider, bug

#695 Support POST-as-GET.
  acme/client.go
  acme/client_test.go
  acme/http.go
Labels: area/lib, enhancement

#698 Support DNS Provider Selectel
  CONTRIBUTING.md
  cli.go
  providers/dns/dns_providers.go
  providers/dns/selectel/client.go
  providers/dns/selectel/selectel.go
  providers/dns/selectel/selectel_test.go
Labels: area/dnsprovider, enhancement

#628 Add DNS Provider for MyDNS.jp
  cli.go
  providers/dns/dns_providers.go
  providers/dns/mydnsjp/mydnsjp.go
  providers/dns/mydnsjp/mydnsjp_test.go
Labels: area/dnsprovider, contrib/waiting-for-feedback, enhancement

#704 fix: Docker image.
  Dockerfile
Labels: bug

#687 Add DNS Provider for inwx
  CONTRIBUTING.md
  Gopkg.lock
  Gopkg.toml
  cli.go
  providers/dns/dns_providers.go
  providers/dns/inwx/inwx.go
  providers/dns/inwx/inwx_test.go
  vendor/github.com/fatih/structs/LICENSE
  vendor/github.com/fatih/structs/field.go
  vendor/github.com/fatih/structs/structs.go
  vendor/github.com/fatih/structs/tags.go
  vendor/github.com/kolo/xmlrpc/LICENSE
  vendor/github.com/kolo/xmlrpc/client.go
  vendor/github.com/kolo/xmlrpc/decoder.go
  vendor/github.com/kolo/xmlrpc/encoder.go
  vendor/github.com/kolo/xmlrpc/request.go
  vendor/github.com/kolo/xmlrpc/response.go
  vendor/github.com/kolo/xmlrpc/xmlrpc.go
  vendor/github.com/mitchellh/mapstructure/LICENSE
  vendor/github.com/mitchellh/mapstructure/decode_hooks.go
  vendor/github.com/mitchellh/mapstructure/error.go
  vendor/github.com/mitchellh/mapstructure/mapstructure.go
  vendor/github.com/smueller18/goinwx/LICENSE
  vendor/github.com/smueller18/goinwx/account.go
  vendor/github.com/smueller18/goinwx/contact.go
  vendor/github.com/smueller18/goinwx/domain.go
  vendor/github.com/smueller18/goinwx/goinwx.go
  vendor/github.com/smueller18/goinwx/nameserver.go
Labels: area/dnsprovider, enhancement

#703 Add DNS Provider for TransIP
  Gopkg.lock
  Gopkg.toml
  providers/dns/dns_providers.go
  providers/dns/transip/fixtures/private.key
  providers/dns/transip/transip.go
  providers/dns/transip/transip_test.go
  vendor/github.com/transip/gotransip/LICENSE
  vendor/github.com/transip/gotransip/api.go
  vendor/github.com/transip/gotransip/client.go
  vendor/github.com/transip/gotransip/domain/api.go
  vendor/github.com/transip/gotransip/domain/domain.go
  vendor/github.com/transip/gotransip/sign.go
  vendor/github.com/transip/gotransip/soap.go
  vendor/github.com/transip/gotransip/util/util.go
Labels: area/dnsprovider, enhancement

#710 Add DNS provider for "HTTP request".
  cli.go
  providers/dns/dns_providers.go
  providers/dns/httpreq/httpreq.go
  providers/dns/httpreq/httpreq_test.go
  providers/dns/httpreq/readme.md
Labels: area/dnsprovider, enhancement

#721 fix: Cloudflare error.
  providers/dns/cloudflare/cloudflare.go
Labels: area/dnsprovider, bug

#719 Add version to xenolf-acme in User-Agent.
  acme/http.go
  acme/http_test.go
Labels: area/lib, enhancement
