Repository go-acme/lego, pull requests merged in 2019-03, with the labels that each got.

#815 OVH: Refresh zone after deleting challenge record
  providers/dns/ovh/ovh.go
Labels: area/dnsprovider, bug

#814 oraclecloud: better way to get private key.
  cmd/cmd_dnshelp.go
  providers/dns/oraclecloud/README.md
  providers/dns/oraclecloud/configprovider.go
  providers/dns/oraclecloud/oraclecloud.go
  providers/dns/oraclecloud/oraclecloud_test.go
Labels: area/dnsprovider, enhancement

#819 Adds log when no renewal.
  cmd/cmd_renew.go
  cmd/cmd_renew_test.go
Labels: area/cli, enhancement

#825 Add 'manual' provider to the output of dnshelp
  cmd/zz_gen_cmd_dnshelp.go
  internal/dnsdocs/dns.go.tmpl
Labels: area/cli, area/dnsprovider, bug

#829 Adds information about _FILE suffix.
  docs/content/dns/_index.md
  docs/content/dns/zz_gen_acme-dns.md
  docs/content/dns/zz_gen_alidns.md
  docs/content/dns/zz_gen_auroradns.md
  docs/content/dns/zz_gen_azure.md
  docs/content/dns/zz_gen_bluecat.md
  docs/content/dns/zz_gen_cloudflare.md
  docs/content/dns/zz_gen_cloudns.md
  docs/content/dns/zz_gen_cloudxns.md
  docs/content/dns/zz_gen_conoha.md
  docs/content/dns/zz_gen_designate.md
  docs/content/dns/zz_gen_digitalocean.md
  docs/content/dns/zz_gen_dnsimple.md
  docs/content/dns/zz_gen_dnsmadeeasy.md
  docs/content/dns/zz_gen_dnspod.md
  docs/content/dns/zz_gen_dreamhost.md
  docs/content/dns/zz_gen_duckdns.md
  docs/content/dns/zz_gen_dyn.md
  docs/content/dns/zz_gen_exoscale.md
  docs/content/dns/zz_gen_fastdns.md
  docs/content/dns/zz_gen_gandi.md
  docs/content/dns/zz_gen_gandiv5.md
  docs/content/dns/zz_gen_gcloud.md
  docs/content/dns/zz_gen_glesys.md
  docs/content/dns/zz_gen_godaddy.md
  docs/content/dns/zz_gen_hostingde.md
  docs/content/dns/zz_gen_httpreq.md
  docs/content/dns/zz_gen_iij.md
  docs/content/dns/zz_gen_inwx.md
  docs/content/dns/zz_gen_lightsail.md
  docs/content/dns/zz_gen_linode.md
  docs/content/dns/zz_gen_linodev4.md
  docs/content/dns/zz_gen_mydnsjp.md
  docs/content/dns/zz_gen_namecheap.md
  docs/content/dns/zz_gen_namedotcom.md
  docs/content/dns/zz_gen_netcup.md
  docs/content/dns/zz_gen_nifcloud.md
  docs/content/dns/zz_gen_ns1.md
  docs/content/dns/zz_gen_oraclecloud.md
  docs/content/dns/zz_gen_otc.md
  docs/content/dns/zz_gen_ovh.md
  docs/content/dns/zz_gen_pdns.md
  docs/content/dns/zz_gen_rackspace.md
  docs/content/dns/zz_gen_rfc2136.md
  docs/content/dns/zz_gen_route53.md
  docs/content/dns/zz_gen_sakuracloud.md
  docs/content/dns/zz_gen_selectel.md
  docs/content/dns/zz_gen_stackpath.md
  docs/content/dns/zz_gen_transip.md
  docs/content/dns/zz_gen_vegadns.md
  docs/content/dns/zz_gen_vscale.md
  docs/content/dns/zz_gen_vultr.md
  docs/content/dns/zz_gen_zoneee.md
  docs/content/usage/cli/_index.md
  internal/dnsdocs/dns.md.tmpl
Labels: area/dnsprovider, area/documentation, enhancement

#832 README: fix link to library usage docs.
  README.md
Labels: area/documentation, bug

#835 Add DNS Provider for Domain Offensive (do.de)
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_dode.md
  providers/dns/dns_providers.go
  providers/dns/dode/client.go
  providers/dns/dode/dode.go
  providers/dns/dode/dode.toml
  providers/dns/dode/dode_test.go
Labels: area/dnsprovider, enhancement

#837 fix pdns: wildcard with SANs
  providers/dns/pdns/client.go
  providers/dns/pdns/pdns.go
Labels: area/dnsprovider, bug

#839 Use provided ZoneName instead of domain for hostingde
  providers/dns/hostingde/hostingde.go
Labels: area/dnsprovider, bug
