Repository go-acme/lego, pull requests merged in 2019-11, with the labels that each got.

#957 Add support for autodns
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_autodns.md
  providers/dns/autodns/autodns.go
  providers/dns/autodns/autodns.toml
  providers/dns/autodns/autodns_test.go
  providers/dns/autodns/client.go
  providers/dns/dns_providers.go
Labels: area/dnsprovider, contrib/waiting-for-correction, enhancement

#1003 fix: use token as unique ID.
  e2e/challenges_test.go
  e2e/dnschallenge/dns_challenges_test.go
  providers/dns/auroradns/auroradns.go
  providers/dns/cloudflare/cloudflare.go
  providers/dns/digitalocean/digitalocean.go
  providers/dns/digitalocean/digitalocean_test.go
  providers/dns/ovh/ovh.go
Labels: area/dnsprovider, bug

#1004 Update ACME RFC links from draft to RFC8555.
  acme/api/api.go
  acme/api/certificate.go
  acme/commons.go
  acme/errors.go
  certificate/certificates.go
  challenge/challenges.go
  challenge/tlsalpn01/tls_alpn_challenge.go
  challenge/tlsalpn01/tls_alpn_challenge_server.go
Labels: area/infrastructure, enhancement

#1005 cloudflare: fix panic when accessing record cache
  providers/dns/cloudflare/cloudflare.go
Labels: bug

#1009 Remove some debug code in e2e tests.
  e2e/challenges_test.go
Labels: area/infrastructure, bug

#1002 Add support to update account
  acme/api/account.go
  e2e/challenges_test.go
  registration/registar.go
Labels: area/lib, enhancement

#1012 Update examples to explain http.webroot
  cmd/flags.go
  docs/content/usage/cli/_index.md
  docs/content/usage/cli/examples.md
Labels: area/documentation, enhancement
