Repository go-acme/lego, pull requests merged in 2019-10, with the labels that each got.

#979 cloudflare: update client
  go.mod
  go.sum
Labels: area/dnsprovider, enhancement

#974 feat: ease operation behind proxy servers
  .golangci.toml
  challenge/http01/domain_matcher.go
  challenge/http01/domain_matcher_test.go
  challenge/http01/http_challenge_server.go
  challenge/http01/http_challenge_test.go
  cmd/flags.go
  cmd/setup_challenges.go
  docs/content/usage/cli/_index.md
Labels: area/cli, enhancement

#983 dreamhost: Add CLI example
  docs/content/dns/zz_gen_dreamhost.md
  providers/dns/dreamhost/dreamhost.toml
Labels: area/dnsprovider, area/documentation, enhancement

#985 cloudflare: handle restricted API tokens
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_cloudflare.md
  providers/dns/cloudflare/client.go
  providers/dns/cloudflare/cloudflare.go
  providers/dns/cloudflare/cloudflare.toml
  providers/dns/cloudflare/cloudflare_test.go
Labels: area/dnsprovider, enhancement

#994 docs: clarify installation-from-source instructions
  docs/content/installation/_index.md
Labels: area/documentation, bug

#996 Don't deactivate valid authorizations
  certificate/authorization.go
Labels: area/lib

#980 feat: expose more SOA fields found by dns01.FindZoneByFqdn
  .golangci.toml
  challenge/dns01/nameserver.go
  challenge/dns01/nameserver_test.go
Labels: area/lib, enhancement

#997 chore: update linter.
  .golangci.toml
  .travis.yml
  acme/api/internal/sender/sender.go
  acme/api/internal/sender/sender_test.go
  challenge/dns01/dns_challenge_test.go
  challenge/dns01/nameserver_test.go
  challenge/http01/domain_matcher.go
  cmd/cmd_renew_test.go
  cmd/zz_gen_cmd_dnshelp.go
  internal/dnsdocs/dns.go.tmpl
  platform/config/env/env_test.go
  providers/dns/alidns/alidns.go
  providers/dns/cloudxns/internal/client_test.go
  providers/dns/conoha/internal/client_test.go
  providers/dns/dnsimple/dnsimple_test.go
  providers/dns/easydns/easydns_test.go
  providers/dns/iij/iij_test.go
  providers/dns/joker/client_test.go
  providers/dns/linodev4/linodev4_test.go
  providers/dns/netcup/internal/client.go
  providers/dns/netcup/internal/client_test.go
  providers/dns/nifcloud/internal/client_test.go
  providers/dns/otc/mock_test.go
  providers/dns/rackspace/rackspace.go
  providers/dns/selectel/internal/client.go
  providers/dns/vscale/internal/client.go
Labels: area/infrastructure, enhancement

#1000 httpreq: Allow use environment vars from a _FILE file
  providers/dns/httpreq/httpreq.go
Labels: area/dnsprovider, enhancement
