Repository go-acme/lego, pull requests merged in 2019-01, with the labels that each got.

#742 gcloud: fix duplicate RR
  .golangci.toml
  providers/dns/gcloud/googlecloud.go
  providers/dns/gcloud/googlecloud_test.go
Labels: area/dnsprovider, bug

#741 New challenges management
  .golangci.toml
  README.md
  challenge/dns01/dns_challenge.go
  challenge/resolver/solver_manager.go
  challenge/resolver/solver_manager_test.go
  cmd/cmd_dnshelp.go
  cmd/flags.go
  cmd/lego/main.go
  cmd/setup_challenges.go
  e2e/challenges_test.go
  e2e/dnschallenge/dns_challenges_test.go
Labels: area/cli, area/lib, enhancement

#750 Use GCE_PROJECT for project always, if specified
  providers/dns/gcloud/googlecloud.go
Labels: area/dnsprovider

#746 contrib: adds a guide to make a pull request.
  CONTRIBUTING.md
Labels: area/infrastructure, enhancement

#752 dns/gcloud: Fix check for GCE_PROJECT when using gcloud
  providers/dns/gcloud/googlecloud.go
Labels: area/dnsprovider, bug

#744 transip: concurrent access to the API.
  providers/dns/transip/transip.go
  providers/dns/transip/transip_test.go
Labels: area/dnsprovider, bug

#748 Change AUR repository.
  README.md
Labels: area/cli, area/infrastructure

#757 chore: updates golangci-lint.
  .travis.yml
  acme/api/internal/secure/jws.go
  acme/api/order_test.go
  challenge/resolver/solver_manager_test.go
  providers/dns/auroradns/auroradns.go
  providers/dns/cloudflare/cloudflare.go
  providers/dns/dnspod/dnspod.go
Labels: area/infrastructure, enhancement

#759 fix: OCSP, set HTTP client.
  acme/api/api.go
Labels: area/lib, bug

#761 gcloud: More detailed information about Google Cloud DNS.
  cmd/cmd_dnshelp.go
  providers/dns/gcloud/googlecloud.go
Labels: area/dnsprovider, enhancement

#765 Change NIFCLOUD DNS base url
  providers/dns/nifcloud/internal/client.go
Labels: area/dnsprovider, enhancement

#767 alicloud: fix pagination.
  providers/dns/alidns/alidns.go
Labels: area/dnsprovider, bug

#764 namecheap: fix panic.
  providers/dns/namecheap/namecheap.go
  providers/dns/namecheap/namecheap_test.go
Labels: area/dnsprovider, bug

#773 Log wildcard domain correctly in validation
  challenge/dns01/dns_challenge.go
  challenge/http01/http_challenge.go
Labels: enhancement
