Repository go-acme/lego, pull requests merged in 2019-08, with the labels that each got.

#945 Fix invalid pseudo version
  .goreleaser.yml
  .travis.yml
  CONTRIBUTING.md
  docs/content/installation/_index.md
  go.mod
  go.sum
Labels: area/infrastructure, bug

#948 fix: invalid pseudo version.
  go.mod
  go.sum
Labels: area/infrastructure, bug

#951 Add Liquid Web DNS Provider
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_liquidweb.md
  go.mod
  go.sum
  providers/dns/dns_providers.go
  providers/dns/liquidweb/liquidweb.go
  providers/dns/liquidweb/liquidweb.toml
  providers/dns/liquidweb/liquidweb_test.go
Labels: area/dnsprovider, enhancement

#954 Fix some typos.
  docs/content/dns/zz_gen_liquidweb.md
  providers/dns/acmedns/acmedns.go
  providers/dns/alidns/alidns.go
  providers/dns/azure/azure.go
  providers/dns/bindman/bindman.go
  providers/dns/bluecat/bluecat.go
  providers/dns/cloudflare/cloudflare.go
  providers/dns/cloudns/cloudns.go
  providers/dns/cloudxns/cloudxns.go
  providers/dns/conoha/conoha.go
  providers/dns/digitalocean/digitalocean.go
  providers/dns/dnsimple/dnsimple.go
  providers/dns/dnsmadeeasy/dnsmadeeasy.go
  providers/dns/dnspod/dnspod.go
  providers/dns/dyn/dyn.go
  providers/dns/easydns/easydns.go
  providers/dns/exoscale/exoscale.go
  providers/dns/fastdns/fastdns.go
  providers/dns/gandi/gandi.go
  providers/dns/gandiv5/gandiv5.go
  providers/dns/glesys/glesys.go
  providers/dns/godaddy/godaddy.go
  providers/dns/hostingde/hostingde.go
  providers/dns/httpreq/httpreq.go
  providers/dns/iij/iij.go
  providers/dns/inwx/inwx.go
  providers/dns/lightsail/lightsail.go
  providers/dns/linode/linode.go
  providers/dns/linodev4/linodev4.go
  providers/dns/liquidweb/liquidweb.go
  providers/dns/liquidweb/liquidweb.toml
  providers/dns/mydnsjp/mydnsjp.go
  providers/dns/namecheap/namecheap.go
  providers/dns/namedotcom/namedotcom.go
  providers/dns/namesilo/namesilo.go
  providers/dns/netcup/netcup.go
  providers/dns/nifcloud/nifcloud.go
  providers/dns/ns1/ns1.go
  providers/dns/oraclecloud/oraclecloud.go
  providers/dns/otc/otc.go
  providers/dns/ovh/ovh.go
  providers/dns/pdns/pdns.go
  providers/dns/rackspace/rackspace.go
  providers/dns/rfc2136/rfc2136.go
  providers/dns/route53/route53.go
  providers/dns/sakuracloud/sakuracloud.go
  providers/dns/selectel/selectel.go
  providers/dns/stackpath/stackpath.go
  providers/dns/versio/versio.go
  providers/dns/vscale/vscale.go
  providers/dns/vultr/vultr.go
  providers/dns/zoneee/zoneee.go
Labels: area/dnsprovider, area/infrastructure, enhancement

#955 doc: fix typesetting of "GitHub"
  CONTRIBUTING.md
  docs/config.toml
Labels: area/documentation, enhancement
