Repository go-acme/lego, pull requests merged in 2019-04, with the labels that each got.

#845 Adds renew hook
  .travis.yml
  acme/api/internal/secure/jws.go
  cmd/cmd_renew.go
  docs/content/usage/cli/examples.md
  internal/dnsdocs/generator.go
  providers/dns/gandiv5/client.go
Labels: area/cli, enhancement

#850 sakuracloud: supports concurrent update
  .golangci.toml
  Gopkg.lock
  Gopkg.toml
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_sakuracloud.md
  providers/dns/sakuracloud/client.go
  providers/dns/sakuracloud/client_test.go
  providers/dns/sakuracloud/sakuracloud.go
  providers/dns/sakuracloud/sakuracloud.toml
  vendor/github.com/sacloud/libsacloud/api/archive.go
  vendor/github.com/sacloud/libsacloud/api/base_api.go
  vendor/github.com/sacloud/libsacloud/api/client.go
  vendor/github.com/sacloud/libsacloud/api/coupon.go
  vendor/github.com/sacloud/libsacloud/api/load_balancer.go
  vendor/github.com/sacloud/libsacloud/api/mobile_gateway.go
  vendor/github.com/sacloud/libsacloud/api/nfs.go
  vendor/github.com/sacloud/libsacloud/api/proxylb.go
  vendor/github.com/sacloud/libsacloud/api/proxylb_gen.go
  vendor/github.com/sacloud/libsacloud/api/sim.go
  vendor/github.com/sacloud/libsacloud/api/simple_monitor.go
  vendor/github.com/sacloud/libsacloud/libsacloud.go
  vendor/github.com/sacloud/libsacloud/sacloud/common_types.go
  vendor/github.com/sacloud/libsacloud/sacloud/coupon.go
  vendor/github.com/sacloud/libsacloud/sacloud/database.go
  vendor/github.com/sacloud/libsacloud/sacloud/interface.go
  vendor/github.com/sacloud/libsacloud/sacloud/loadbalancer.go
  vendor/github.com/sacloud/libsacloud/sacloud/lock.go
  vendor/github.com/sacloud/libsacloud/sacloud/mobile_gateway.go
  vendor/github.com/sacloud/libsacloud/sacloud/monitor.go
  vendor/github.com/sacloud/libsacloud/sacloud/nfs.go
  vendor/github.com/sacloud/libsacloud/sacloud/ostype/archive_ostype.go
  vendor/github.com/sacloud/libsacloud/sacloud/ostype/archiveostypes_string.go
  vendor/github.com/sacloud/libsacloud/sacloud/proxylb.go
  vendor/github.com/sacloud/libsacloud/sacloud/server.go
  vendor/github.com/sacloud/libsacloud/sacloud/sim.go
  vendor/github.com/sacloud/libsacloud/sacloud/simple_monitor.go
  vendor/github.com/sacloud/libsacloud/sacloud/switch.go
  vendor/github.com/sacloud/libsacloud/sacloud/vpc_router.go
  vendor/github.com/sacloud/libsacloud/sacloud/vpc_router_status.go
  vendor/github.com/sacloud/libsacloud/utils/mutexkv/mutexkv.go
Labels: area/dnsprovider, bug

#851 Disable authz when solve fail.
  certificate/certificates.go
Labels: area/dnsprovider, bug

#853 route53: enhance documentation.
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_route53.md
  providers/dns/route53/route53.toml
Labels: area/dnsprovider, area/documentation, enhancement

#856 cloudns: fix TTL and status validation
  providers/dns/cloudns/cloudns.go
  providers/dns/cloudns/internal/client.go
  providers/dns/cloudns/internal/client_test.go
Labels: area/dnsprovider, bug

#863 Add tzdata to the Docker image.
  Dockerfile
Labels: bug

#861 Use fqdn to get zone in gcloud Present/CleanUp
  providers/dns/gcloud/googlecloud.go
Labels: area/dnsprovider, bug

#869 Add support for Bindman DNS provider
  Gopkg.lock
  Gopkg.toml
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_bindman.md
  providers/dns/bindman/bindman.go
  providers/dns/bindman/bindman.toml
  providers/dns/bindman/bindman_test.go
  providers/dns/dns_providers.go
  vendor/github.com/go-errors/errors/LICENSE.MIT
  vendor/github.com/go-errors/errors/error.go
  vendor/github.com/go-errors/errors/parse_panic.go
  vendor/github.com/go-errors/errors/stackframe.go
  vendor/github.com/labbsr0x/bindman-dns-webhook/LICENSE
  vendor/github.com/labbsr0x/bindman-dns-webhook/src/client/client.go
  vendor/github.com/labbsr0x/bindman-dns-webhook/src/types/dnsmanager.go
  vendor/github.com/labbsr0x/bindman-dns-webhook/src/types/dnsrecord.go
  vendor/github.com/labbsr0x/bindman-dns-webhook/src/types/error.go
  vendor/github.com/labbsr0x/goh/LICENSE
  vendor/github.com/labbsr0x/goh/gohclient/gohclient.go
Labels: area/dnsprovider, enhancement

#870 Add support for Joker.com DMAPI
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_joker.md
  providers/dns/dns_providers.go
  providers/dns/joker/client.go
  providers/dns/joker/client_test.go
  providers/dns/joker/joker.go
  providers/dns/joker/joker.toml
  providers/dns/joker/joker_test.go
Labels: area/dnsprovider, enhancement

#867 Add support for EasyDNS
  Makefile
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_easydns.md
  providers/dns/dns_providers.go
  providers/dns/easydns/client.go
  providers/dns/easydns/easydns.go
  providers/dns/easydns/easydns.toml
  providers/dns/easydns/easydns_test.go
Labels: area/dnsprovider, enhancement
