Repository go-acme/lego, pull requests merged in 2019-02, with the labels that each got.

#776 option to specify gcloud service account json by env as string
  cmd/cmd_dnshelp.go
  providers/dns/gcloud/googlecloud.go
  providers/dns/gcloud/googlecloud_test.go
Labels: area/dnsprovider, enhancement

#774 fastdns: Do not overwrite existing TXT records
  Gopkg.lock
  Gopkg.toml
  providers/dns/fastdns/fastdns.go
  vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/client-v1/client.go
  vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/client-v1/errors.go
  vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/configdns-v1/record.go
  vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/configdns-v1/zone.go
  vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/jsonhooks-v1/jsonhooks.go
  vendor/github.com/google/uuid/dce.go
  vendor/github.com/google/uuid/hash.go
  vendor/github.com/google/uuid/marshal.go
  vendor/github.com/google/uuid/node.go
  vendor/github.com/google/uuid/node_js.go
  vendor/github.com/google/uuid/node_net.go
  vendor/github.com/google/uuid/sql.go
  vendor/github.com/google/uuid/time.go
  vendor/github.com/google/uuid/uuid.go
  vendor/github.com/google/uuid/version1.go
  vendor/github.com/google/uuid/version4.go
Labels: area/dnsprovider, bug

#781 httpreq: Endpoint with path.
  providers/dns/httpreq/httpreq.go
  providers/dns/httpreq/httpreq_test.go
Labels: area/dnsprovider, bug

#782 chore: update golangci-lint.
  .golangci.toml
  .travis.yml
  acme/api/certificate_test.go
  acme/api/internal/nonces/nonce_manager_test.go
  acme/api/internal/secure/jws_test.go
  acme/api/internal/sender/sender_test.go
  certificate/certificates_test.go
  providers/dns/azure/azure_test.go
  providers/dns/netcup/internal/client_test.go
  providers/dns/nifcloud/internal/client_test.go
  providers/dns/otc/mock_test.go
  providers/dns/rackspace/rackspace_test.go
  providers/dns/stackpath/stackpath_test.go
  providers/dns/vegadns/vegadns_test.go
  registration/registar_test.go
Labels: area/infrastructure, enhancement

#786 Add support for Openstack Designate as a DNS provider
  CONTRIBUTING.md
  Gopkg.lock
  cmd/cmd_dnshelp.go
  providers/dns/designate/designate.go
  providers/dns/designate/designate_test.go
  providers/dns/dns_providers.go
  vendor/github.com/gophercloud/gophercloud/LICENSE
  vendor/github.com/gophercloud/gophercloud/auth_options.go
  vendor/github.com/gophercloud/gophercloud/doc.go
  vendor/github.com/gophercloud/gophercloud/endpoint_search.go
  vendor/github.com/gophercloud/gophercloud/errors.go
  vendor/github.com/gophercloud/gophercloud/openstack/auth_env.go
  vendor/github.com/gophercloud/gophercloud/openstack/client.go
  vendor/github.com/gophercloud/gophercloud/openstack/dns/v2/recordsets/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/dns/v2/recordsets/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/dns/v2/recordsets/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/dns/v2/recordsets/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/dns/v2/zones/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/dns/v2/zones/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/dns/v2/zones/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/dns/v2/zones/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/endpoint_location.go
  vendor/github.com/gophercloud/gophercloud/openstack/errors.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v2/tenants/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v2/tenants/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v2/tenants/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v2/tenants/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v2/tokens/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v2/tokens/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v2/tokens/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v2/tokens/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/tokens/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/tokens/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/tokens/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/tokens/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/utils/base_endpoint.go
  vendor/github.com/gophercloud/gophercloud/openstack/utils/choose_version.go
  vendor/github.com/gophercloud/gophercloud/pagination/http.go
  vendor/github.com/gophercloud/gophercloud/pagination/linked.go
  vendor/github.com/gophercloud/gophercloud/pagination/marker.go
  vendor/github.com/gophercloud/gophercloud/pagination/pager.go
  vendor/github.com/gophercloud/gophercloud/pagination/pkg.go
  vendor/github.com/gophercloud/gophercloud/pagination/single.go
  vendor/github.com/gophercloud/gophercloud/params.go
  vendor/github.com/gophercloud/gophercloud/provider_client.go
  vendor/github.com/gophercloud/gophercloud/results.go
  vendor/github.com/gophercloud/gophercloud/service_client.go
  vendor/github.com/gophercloud/gophercloud/util.go
Labels: area/dnsprovider, enhancement

#787 Applies Let’s Encrypt’s recommendation about renew.
  cmd/cmd_renew.go
Labels: area/cli, enhancement

#789 removing `lego` from the dockerignore
  .dockerignore
Labels: area/infrastructure, bug

#790 fix: CLI and key type.
  certcrypto/crypto.go
  cmd/accounts_storage.go
  cmd/flags.go
  cmd/setup.go
Labels: area/cli, bug

#791 Resolve CNAME when creating dns-01 challenge
  challenge/dns01/cname.go
  challenge/dns01/dns_challenge.go
  challenge/dns01/precheck.go
Labels: area/lib, enhancement

#794 Uses a jittered exponential backoff
  Gopkg.lock
  acme/api/api.go
  challenge/resolver/solver_manager.go
  vendor/github.com/cenkalti/backoff/LICENSE
  vendor/github.com/cenkalti/backoff/backoff.go
  vendor/github.com/cenkalti/backoff/context.go
  vendor/github.com/cenkalti/backoff/exponential.go
  vendor/github.com/cenkalti/backoff/retry.go
  vendor/github.com/cenkalti/backoff/ticker.go
  vendor/github.com/cenkalti/backoff/tries.go
Labels: area/lib, bug

#783 Add a mechanism to wrap a PreCheckFunc
  challenge/dns01/dns_challenge.go
  challenge/dns01/dns_challenge_test.go
  challenge/dns01/precheck.go
Labels: area/dnsprovider, enhancement

#797 fix: TXT records clean up for Selectel DNS provider
  providers/dns/selectel/selectel.go
Labels: area/dnsprovider, bug

#798 fix: TXT records clean up for Vscale DNS provider
  providers/dns/vscale/vscale.go
Labels: area/dnsprovider, bug

#803 selectel: getting sub-domain
  providers/dns/selectel/internal/client.go
Labels: area/dnsprovider, bug

#805 vscale: getting sub-domain
  providers/dns/vscale/internal/client.go
Labels: area/dnsprovider, bug

#809 bugfix hostingde client fails if customer has no access to dns-groups
  providers/dns/hostingde/client.go
  providers/dns/hostingde/hostingde.go
  providers/dns/hostingde/model.go
Labels: area/dnsprovider, bug

#799 chore: update golangci-lint.
  .golangci.toml
  .travis.yml
  cmd/cmd_run.go
  providers/dns/sakuracloud/sakuracloud.go
Labels: area/infrastructure, enhancement

#812 OracleCloud: ttl config and timeout
  providers/dns/oraclecloud/oraclecloud.go
Labels: area/dnsprovider, bug
