Repository go-acme/lego, pull requests merged in 2019-07, with the labels that each got.

#913 Improve Cloudflare documentation.
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_cloudflare.md
  platform/config/env/env_test.go
  providers/dns/cloudflare/cloudflare.toml
Labels: area/documentation, enhancement

#914 Update golangci-lint.
  .golangci.toml
  .travis.yml
Labels: area/infrastructure, enhancement

#916 Add DNS provider for namesilo
  Gopkg.lock
  Gopkg.toml
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_namesilo.md
  providers/dns/dns_providers.go
  providers/dns/namesilo/namesilo.go
  providers/dns/namesilo/namesilo.toml
  providers/dns/namesilo/namesilo_test.go
  vendor/github.com/nrdcg/namesilo/LICENSE
  vendor/github.com/nrdcg/namesilo/auth.go
  vendor/github.com/nrdcg/namesilo/model.go
  vendor/github.com/nrdcg/namesilo/namesilo.go
  vendor/github.com/nrdcg/namesilo/params.go
  vendor/github.com/nrdcg/namesilo/zz_gen_client.go
Labels: area/dnsprovider, enhancement

#922 fix: confusing message.
  certificate/authorization.go
Labels: area/lib, bug

#923 Handles write errors when displaying DNS help.
  cmd/cmd_dnshelp.go
  cmd/zz_gen_cmd_dnshelp.go
  internal/dnsdocs/dns.go.tmpl
Labels: area/cli, area/dnsprovider, bug

#920 namesilo: fix link in the readme.
  README.md
Labels: area/dnsprovider, area/documentation, bug

#924 Too early deprecation.
  registration/registar.go
Labels: area/lib, bug

#927 joker: support username and password.
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_joker.md
  providers/dns/joker/client.go
  providers/dns/joker/client_test.go
  providers/dns/joker/joker.go
  providers/dns/joker/joker.toml
  providers/dns/joker/joker_test.go
Labels: area/dnsprovider, enhancement

#929 Switch Vultr to official client
  Gopkg.lock
  Gopkg.toml
  docs/content/dns/zz_gen_vultr.md
  providers/dns/vultr/vultr.go
  providers/dns/vultr/vultr.toml
  vendor/github.com/JamesClonk/vultr/lib/account_info.go
  vendor/github.com/JamesClonk/vultr/lib/applications.go
  vendor/github.com/JamesClonk/vultr/lib/block_storage.go
  vendor/github.com/JamesClonk/vultr/lib/client.go
  vendor/github.com/JamesClonk/vultr/lib/dns.go
  vendor/github.com/JamesClonk/vultr/lib/firewall.go
  vendor/github.com/JamesClonk/vultr/lib/ip.go
  vendor/github.com/JamesClonk/vultr/lib/iso.go
  vendor/github.com/JamesClonk/vultr/lib/os.go
  vendor/github.com/JamesClonk/vultr/lib/plans.go
  vendor/github.com/JamesClonk/vultr/lib/regions.go
  vendor/github.com/JamesClonk/vultr/lib/reservedip.go
  vendor/github.com/JamesClonk/vultr/lib/scripts.go
  vendor/github.com/JamesClonk/vultr/lib/servers.go
  vendor/github.com/JamesClonk/vultr/lib/snapshots.go
  vendor/github.com/JamesClonk/vultr/lib/sshkeys.go
  vendor/github.com/juju/ratelimit/LICENSE
  vendor/github.com/juju/ratelimit/ratelimit.go
  vendor/github.com/juju/ratelimit/reader.go
  vendor/github.com/vultr/govultr/LICENSE
  vendor/github.com/vultr/govultr/account.go
  vendor/github.com/vultr/govultr/api.go
  vendor/github.com/vultr/govultr/application.go
  vendor/github.com/vultr/govultr/backup.go
  vendor/github.com/vultr/govultr/bare_metal_server.go
  vendor/github.com/vultr/govultr/block_storage.go
  vendor/github.com/vultr/govultr/dns_domains.go
  vendor/github.com/vultr/govultr/dns_records.go
  vendor/github.com/vultr/govultr/firewall_group.go
  vendor/github.com/vultr/govultr/firewall_rule.go
  vendor/github.com/vultr/govultr/govultr.go
  vendor/github.com/vultr/govultr/iso.go
  vendor/github.com/vultr/govultr/network.go
  vendor/github.com/vultr/govultr/os.go
  vendor/github.com/vultr/govultr/plans.go
  vendor/github.com/vultr/govultr/regions.go
  vendor/github.com/vultr/govultr/reserved_ip.go
  vendor/github.com/vultr/govultr/server.go
  vendor/github.com/vultr/govultr/snapshot.go
  vendor/github.com/vultr/govultr/ssh_key.go
  vendor/github.com/vultr/govultr/startup_script.go
  vendor/github.com/vultr/govultr/user.go
Labels: area/dnsprovider, enhancement

#932 vultr: invalid record type.
  providers/dns/vultr/vultr.go
Labels: area/dnsprovider, bug

#935 Add install instructions for FreeBSD ports
  docs/content/installation/_index.md
Labels: area/cli, area/documentation, enhancement

#940 vultr: quote TXT record
  providers/dns/vultr/vultr.go
Labels: area/dnsprovider, bug
