Repository go-acme/lego, pull requests merged in 2019-09, with the labels that each got.

#937 cloudflare: add support for API tokens
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_cloudflare.md
  providers/dns/cloudflare/cloudflare.go
  providers/dns/cloudflare/cloudflare.toml
  providers/dns/cloudflare/cloudflare_test.go
Labels: area/dnsprovider, enhancement

#962 chore: update to go1.13
  .golangci.toml
  .travis.yml
  Dockerfile
  go.mod
  go.sum
Labels: area/infrastructure, enhancement

#961 linodev4: propagation timeout configuration.
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_linodev4.md
  providers/dns/linodev4/linodev4.go
  providers/dns/linodev4/linodev4.toml
Labels: area/dnsprovider, enhancement

#971 bindman: fix client version.
  go.mod
  go.sum
Labels: area/dnsprovider, bug

#972 ovh: fix int overflow.
  providers/dns/ovh/ovh.go
Labels: area/dnsprovider, bug
