Repository go-acme/lego, pull requests merged in 2019-05, with the labels that each got.

#875 gcloud: fix zone visibility.
  providers/dns/gcloud/googlecloud.go
Labels: area/dnsprovider, bug

#868 fix: cli disable-cp option.
  cmd/setup_challenges.go
Labels: area/cli, bug

#881 exec: serial behavior
  providers/dns/exec/exec.go
Labels: area/dnsprovider, bug

#864 Check if the generation of DNS documentation has been successfully completed.
  .travis.yml
  Makefile
Labels: area/dnsprovider, area/documentation, area/infrastructure, enhancement

#878 doc: adds some missing information.
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_exec.md
  docs/content/dns/zz_gen_godaddy.md
  docs/content/dns/zz_gen_hostingde.md
  docs/content/dns/zz_gen_httpreq.md
  providers/dns/exec/exec.toml
  providers/dns/godaddy/godaddy.toml
  providers/dns/hostingde/hostingde.toml
  providers/dns/httpreq/httpreq.toml
Labels: area/documentation, enhancement

#880 manual: serial behavior.
  challenge/dns01/dns_challenge_manual.go
Labels: area/dnsprovider, bug

#872 Strip newlines when reading environment variables from `_FILE` suffixed files.
  platform/config/env/env.go
  platform/config/env/env_test.go
Labels: area/dnsprovider, bug

#885 digitalocean: LEGO_EXPERIMENTAL_CNAME_SUPPORT support
  providers/dns/digitalocean/client.go
  providers/dns/digitalocean/digitalocean.go
Labels: area/dnsprovider, bug

#897 Get an existing certificate by URL
  certificate/certificates.go
  certificate/certificates_test.go
Labels: area/lib, enhancement

#898 CLI help indentation.
  cmd/cmd_dnshelp.go
  cmd/zz_gen_cmd_dnshelp.go
  internal/dnsdocs/dns.go.tmpl
Labels: area/cli, enhancement
