Repository go-acme/lego, pull requests merged in 2020-04, with the labels that each got.

#1105 ns1: fix missing domain in log
  providers/dns/ns1/ns1.go
Labels: area/dnsprovider, bug

#1109 Improve Name.com documentation
  docs/content/dns/zz_gen_namedotcom.md
  providers/dns/namedotcom/namedotcom.toml
Labels: area/dnsprovider, area/documentation, enhancement

#1108 Informations about renewed certificates are now passed to the renew hook
  cmd/certs_storage.go
  cmd/cmd_renew.go
  docs/content/usage/cli/examples.md
Labels: area/cli

#1111 alicloud: update sdk dependency version to v1.61.112
  go.mod
  go.sum
Labels: area/dnsprovider, bug

#1112 rimuhosting: use HTTP client from config.
  providers/dns/rimuhosting/rimuhosting.go
  providers/dns/zonomi/zonomi.go
Labels: area/dnsprovider, bug

#1110 azure: Allow for the use of MSI
  go.mod
  providers/dns/azure/azure.go
Labels: area/dnsprovider, enhancement

#1114 godaddy: allow parallel solve.
  providers/dns/godaddy/client.go
  providers/dns/godaddy/godaddy.go
Labels: area/dnsprovider, enhancement

#1115 constellix: improve challenge.
  providers/dns/constellix/constellix.go
  providers/dns/constellix/internal/client.go
  providers/dns/constellix/internal/domains.go
  providers/dns/constellix/internal/domains_test.go
  providers/dns/constellix/internal/fixtures/domains-GetAll.json
  providers/dns/constellix/internal/fixtures/domains-Search.json
  providers/dns/constellix/internal/fixtures/records-Create.json
  providers/dns/constellix/internal/fixtures/records-Get.json
  providers/dns/constellix/internal/fixtures/records-GetAll.json
  providers/dns/constellix/internal/fixtures/records-Search.json
  providers/dns/constellix/internal/model.go
  providers/dns/constellix/internal/txtrecords.go
  providers/dns/constellix/internal/txtrecords_test.go
Labels: area/dnsprovider, enhancement

#1104 transip: updated the client to v6
  docs/content/dns/zz_gen_transip.md
  go.mod
  go.sum
  providers/dns/transip/fakeclient_test.go
  providers/dns/transip/transip.go
  providers/dns/transip/transip.toml
  providers/dns/transip/transip_test.go
Labels: area/dnsprovider, enhancement

#1116 fix: some typos.
  docs/content/dns/zz_gen_gcloud.md
  docs/content/dns/zz_gen_liquidweb.md
  providers/dns/gcloud/gcloud.toml
  providers/dns/liquidweb/liquidweb.toml
  providers/dns/namedotcom/namedotcom.go
Labels: area/dnsprovider, area/documentation, bug

#1106 Add DNS provider for CloudDNS.
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_clouddns.md
  providers/dns/clouddns/clouddns.go
  providers/dns/clouddns/clouddns.toml
  providers/dns/clouddns/clouddns_test.go
  providers/dns/clouddns/internal/client.go
  providers/dns/clouddns/internal/client_test.go
  providers/dns/clouddns/internal/models.go
  providers/dns/dns_providers.go
Labels: area/dnsprovider, enhancement

#953 Add DNS provider for Yandex.
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_yandex.md
  providers/dns/dns_providers.go
  providers/dns/yandex/internal/client.go
  providers/dns/yandex/internal/client_test.go
  providers/dns/yandex/internal/types.go
  providers/dns/yandex/yandex.go
  providers/dns/yandex/yandex.toml
  providers/dns/yandex/yandex_test.go
Labels: area/dnsprovider, enhancement

#1127 Fix account storage location warning message
  cmd/cmd_run.go
Labels: area/cli, enhancement

#1125 Add DNS provider for Mythic beasts DNSv2
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_mythicbeasts.md
  providers/dns/dns_providers.go
  providers/dns/mythicbeasts/client.go
  providers/dns/mythicbeasts/mythicbeasts.go
  providers/dns/mythicbeasts/mythicbeasts.toml
  providers/dns/mythicbeasts/mythicbeasts_test.go
Labels: area/dnsprovider, enhancement

#1130 Fix exoscale HTTP timeout
  providers/dns/exoscale/exoscale.go
Labels: area/dnsprovider, bug
