Repository go-acme/lego, pull requests merged in 2020-03, with the labels that each got.

#1072 feat: multi-arch Docker image.
  .travis.yml
  Dockerfile
  Makefile
  tmpl.Dockerfile
Labels: area/cli, area/infrastructure, enhancement

#1079 Build improvements
  .goreleaser.yml
  Makefile
  go.mod
  go.sum
Labels: area/cli, enhancement

#1073 Upgrade `cloud.google.com/go` to 0.53
  go.mod
  go.sum
Labels: area/dnsprovider

#1080 Generating DNS providers table in the README.
  README.md
  internal/dnsdocs/generator.go
Labels: area/documentation, area/infrastructure, enhancement

#1076 lib: Improve cleanup log messages.
  challenge/http01/http_challenge.go
  challenge/resolver/prober.go
  challenge/tlsalpn01/tls_alpn_challenge.go
Labels: area/lib, enhancement

#1078 Add DNS provider for reg.ru
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_regru.md
  providers/dns/dns_providers.go
  providers/dns/regru/internal/client.go
  providers/dns/regru/internal/client_test.go
  providers/dns/regru/internal/model.go
  providers/dns/regru/regru.go
  providers/dns/regru/regru.toml
  providers/dns/regru/regru_test.go
Labels: area/dnsprovider, enhancement

#1081 Add DNS provider for Dynu.
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_dynu.md
  providers/dns/dns_providers.go
  providers/dns/dynu/dynu.go
  providers/dns/dynu/dynu.toml
  providers/dns/dynu/dynu_test.go
  providers/dns/dynu/internal/auth.go
  providers/dns/dynu/internal/auth_test.go
  providers/dns/dynu/internal/client.go
  providers/dns/dynu/internal/client_test.go
  providers/dns/dynu/internal/fixtures/add_new_record.json
  providers/dns/dynu/internal/fixtures/add_new_record_invalid.json
  providers/dns/dynu/internal/fixtures/delete_record.json
  providers/dns/dynu/internal/fixtures/delete_record_invalid.json
  providers/dns/dynu/internal/fixtures/get_records.json
  providers/dns/dynu/internal/fixtures/get_records_empty.json
  providers/dns/dynu/internal/fixtures/get_records_invalid.json
  providers/dns/dynu/internal/fixtures/get_root_domain.json
  providers/dns/dynu/internal/fixtures/get_root_domain_invalid.json
  providers/dns/dynu/internal/model.go
Labels: area/dnsprovider, enhancement

#1055 oraclecloud: fix subdomain support
  providers/dns/oraclecloud/oraclecloud.go
Labels: area/dnsprovider

#1046 Adds --name flag to list command.
  cmd/cmd_list.go
Labels: area/cli

#1083 azure: pass AZURE_CLIENT_SECRET_FILE to autorest.Authorizer
  providers/dns/azure/azure.go
Labels: area/dnsprovider, bug

#1084 Add DNS provider for Zonomi and RimuHosting.
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_rimuhosting.md
  docs/content/dns/zz_gen_zonomi.md
  providers/dns/dns_providers.go
  providers/dns/internal/rimuhosting/client.go
  providers/dns/internal/rimuhosting/client_test.go
  providers/dns/internal/rimuhosting/fixtures/add_record.xml
  providers/dns/internal/rimuhosting/fixtures/add_record_error.xml
  providers/dns/internal/rimuhosting/fixtures/add_record_same_domain.xml
  providers/dns/internal/rimuhosting/fixtures/delete_record.xml
  providers/dns/internal/rimuhosting/fixtures/delete_record_error.xml
  providers/dns/internal/rimuhosting/fixtures/delete_record_nothing.xml
  providers/dns/internal/rimuhosting/fixtures/find_records.xml
  providers/dns/internal/rimuhosting/fixtures/find_records_empty.xml
  providers/dns/internal/rimuhosting/fixtures/find_records_pattern.xml
  providers/dns/internal/rimuhosting/model.go
  providers/dns/rimuhosting/rimuhosting.go
  providers/dns/rimuhosting/rimuhosting.toml
  providers/dns/rimuhosting/rimuhosting_test.go
  providers/dns/zonomi/zonomi.go
  providers/dns/zonomi/zonomi.toml
  providers/dns/zonomi/zonomi_test.go
Labels: area/dnsprovider, enhancement

#1085 Share the client code between Selectel and VScale.
  providers/dns/internal/selectel/client.go
  providers/dns/internal/selectel/client_test.go
  providers/dns/internal/selectel/fixtures/domains.json
  providers/dns/internal/selectel/fixtures/error.json
  providers/dns/internal/selectel/fixtures/list_records.json
  providers/dns/internal/selectel/models.go
  providers/dns/selectel/selectel.go
  providers/dns/vscale/internal/client.go
  providers/dns/vscale/vscale.go
Labels: area/dnsprovider, enhancement

#545 namedotcom: get the actual registered domain so we can remove just that from the hostname to be created
  providers/dns/namedotcom/namedotcom.go
Labels: area/dnsprovider, enhancement

#1088 alicloud: add support for domain with punycode
  providers/dns/alidns/alidns.go
Labels: area/dnsprovider, bug

#1090 Use colon instead a arrow in error messages
  acme/api/api.go
  acme/api/internal/nonces/nonce_manager.go
  acme/api/internal/secure/jws.go
  certificate/errors.go
  challenge/http01/http_challenge_server.go
  challenge/resolver/errors.go
  challenge/resolver/prober_test.go
  challenge/tlsalpn01/tls_alpn_challenge_server.go
  cmd/accounts_storage.go
  providers/dns/pdns/client.go
  providers/http/memcached/memcached.go
  providers/http/webroot/webroot.go
Labels: area/lib, enhancement

#1094 fix: broken link to port usage section.
  docs/content/usage/cli/_index.md
Labels: area/documentation, bug

#1095 acmedns: Update cpu/goacmedns v0.0.1 -> v0.0.2
  go.mod
  go.sum
Labels: area/dnsprovider, enhancement

#1098 Provider ClouDNS: Add subuser support
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_cloudns.md
  providers/dns/cloudns/cloudns.go
  providers/dns/cloudns/cloudns.toml
  providers/dns/cloudns/cloudns_test.go
  providers/dns/cloudns/internal/client.go
  providers/dns/cloudns/internal/client_test.go
Labels: area/dnsprovider
