Repository go-acme/lego, pull requests merged in 2020-06, with the labels that each got.

#1179 binaries: Add MIPS arch.
  .goreleaser.yml
Labels: area/infrastructure, enhancement

#1182 doc: fix example of env vars file.
  docs/content/dns/_index.md
Labels: area/documentation, bug

#1193 vultr: bumping govultr version
  go.mod
  go.sum
Labels: area/dnsprovider, enhancement

#1199 hetzner: fix record name.
  providers/dns/hetzner/hetzner.go
Labels: area/dnsprovider, bug

#1202 arvandcloud: fix: record name.
  providers/dns/alidns/alidns.go
  providers/dns/arvancloud/arvancloud.go
  providers/dns/dnsimple/dnsimple.go
  providers/dns/dnspod/dnspod.go
  providers/dns/godaddy/godaddy.go
  providers/dns/namedotcom/namedotcom.go
  providers/dns/ovh/ovh.go
  providers/dns/sakuracloud/client.go
  providers/dns/vultr/vultr.go
Labels: area/dnsprovider, bug

#1201 fix: multi-va.
  challenge/dns01/dns_challenge.go
Labels: area/dnsprovider, bug

#1203 doc: improvements.
  README.md
  providers/dns/oraclecloud/oraclecloud.go
Labels: area/documentation, enhancement

#1200 constellix: fix search records API call.
  providers/dns/constellix/constellix.go
  providers/dns/constellix/internal/fixtures/records-Search.json
Labels: area/dnsprovider, bug

#1204 stackpath: fix subdomain support.
  providers/dns/stackpath/stackpath.go
Labels: area/dnsprovider, bug
