Repository go-acme/lego, pull requests merged in 2020-09, with the labels that each got.

#1240 namesilo: fix cleanup.
  providers/dns/namesilo/namesilo.go
Labels: area/dnsprovider, bug

#1227 add --preferred-chain option to support "alternate" certificate links
  acme/api/order.go
  acme/api/order_test.go
  acme/api/service.go
  acme/commons.go
  certificate/certificates.go
  certificate/certificates_test.go
  cmd/cmd_renew.go
  cmd/cmd_run.go
  e2e/challenges_test.go
Labels: area/cli, area/lib, enhancement

#1244 exoscale: change dependency version.
  go.mod
  go.sum
Labels: bug

#1258 gcloud: adds an option to allow the use of private zones
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_gcloud.md
  providers/dns/gcloud/gcloud.toml
  providers/dns/gcloud/googlecloud.go
Labels: area/dnsprovider, enhancement

#1259 rfc2136: ensure TSIG algorithm is fully qualified
  providers/dns/rfc2136/rfc2136.go
Labels: area/dnsprovider, enhancement

#1260 chore: spell check docs
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/_index.md
  docs/content/dns/zz_gen_autodns.md
  docs/content/dns/zz_gen_cloudxns.md
  docs/content/dns/zz_gen_dyn.md
  docs/content/dns/zz_gen_edgedns.md
  docs/content/dns/zz_gen_mythicbeasts.md
  docs/content/dns/zz_gen_oraclecloud.md
  docs/content/dns/zz_gen_pdns.md
  docs/content/dns/zz_gen_rfc2136.md
  docs/content/dns/zz_gen_vscale.md
  docs/content/usage/cli/_index.md
  docs/content/usage/library/Writing-a-Challenge-Solver.md
  docs/content/usage/library/_index.md
  providers/dns/autodns/autodns.toml
  providers/dns/bindman/bindman.toml
  providers/dns/cloudxns/cloudxns.toml
  providers/dns/dyn/dyn.toml
  providers/dns/edgedns/edgedns.toml
  providers/dns/mythicbeasts/mythicbeasts.toml
  providers/dns/oraclecloud/oraclecloud.toml
  providers/dns/pdns/pdns.toml
  providers/dns/rfc2136/rfc2136.toml
  providers/dns/vscale/vscale.toml
Labels: area/documentation, bug

#1261 Fix minor typo in docs
  certificate/certificates.go
Labels: area/documentation, bug
