Repository go-acme/lego, pull requests merged in 2020-01, with the labels that each got.

#1027 dns/dreamhost: fix GoDoc
  providers/dns/dreamhost/dreamhost.go
Labels: area/documentation, bug

#1028 Auto-detection of the project ID for gcloud.
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_gcloud.md
  go.mod
  go.sum
  providers/dns/gcloud/gcloud.toml
  providers/dns/gcloud/googlecloud.go
  providers/dns/gcloud/googlecloud_test.go
Labels: area/dnsprovider, enhancement

#1030 Successfully parse private key PEM blocks
  certcrypto/crypto.go
Labels: area/lib, enhancement

#1034 Update dnspod, because of API breaking changes.
  docs/content/dns/zz_gen_dnspod.md
  go.mod
  go.sum
  providers/dns/dnspod/dnspod.go
  providers/dns/dnspod/dnspod.toml
Labels: area/dnsprovider, bug

#1036 doc: improve Route53 documentation.
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_route53.md
  providers/dns/route53/route53.toml
Labels: area/dnsprovider, area/documentation, enhancement

#1037 Update dnspod lib.
  go.mod
  go.sum
  providers/dns/dnspod/dnspod.go
Labels: area/dnsprovider, enhancement

#1041 namecheap: add sandbox support.
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_namecheap.md
  providers/dns/namecheap/namecheap.go
  providers/dns/namecheap/namecheap.toml
Labels: area/dnsprovider, enhancement

#1043 chore: update cenkalti/backoff to v4.
  acme/api/api.go
  challenge/resolver/solver_manager.go
  go.mod
  go.sum
  providers/dns/hostingde/client.go
Labels: area/lib, bug

#1044 designate: Don't clean up managed records like SOA and NS
  providers/dns/designate/designate.go
Labels: area/dnsprovider, bug

#1042 namecheap: allow external domains
  .golangci.toml
  providers/dns/namecheap/client.go
  providers/dns/namecheap/namecheap.go
  providers/dns/namecheap/namecheap_test.go
Labels: area/dnsprovider, enhancement

#1045 Add "LEGO_PATH" environment variable
  cmd/flags.go
  cmd/lego/main.go
Labels: area/cli, enhancement

#1047 Add DNS provider for Scaleway
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_scaleway.md
  providers/dns/dns_providers.go
  providers/dns/scaleway/internal/client.go
  providers/dns/scaleway/internal/client_test.go
  providers/dns/scaleway/scaleway.go
  providers/dns/scaleway/scaleway.toml
  providers/dns/scaleway/scaleway_test.go
Labels: area/dnsprovider, enhancement
