Repository go-acme/lego, pull requests merged in 2020-02, with the labels that each got.

#1050 route53: allow custom client to be provided
  providers/dns/route53/route53.go
Labels: area/dnsprovider, enhancement

#1053 zoneee: fix subdomains.
  providers/dns/zoneee/zoneee.go
  providers/dns/zoneee/zoneee_test.go
Labels: area/dnsprovider, bug

#1057 ovh: Improve provider documentation
  docs/content/dns/zz_gen_ovh.md
  providers/dns/ovh/ovh.toml
Labels: area/dnsprovider, area/documentation, enhancement

#1059 Minors changes
  .golangci.toml
  acme/api/api.go
  providers/dns/checkdomain/checkdomain.go
  providers/dns/checkdomain/client.go
  providers/dns/selectel/internal/client.go
  providers/dns/vscale/internal/client.go
  providers/dns/zoneee/zoneee_test.go
Labels: area/infrastructure, enhancement

#1064 crypto: Treat CommonName as optional
  certcrypto/crypto.go
Labels: area/lib, bug

#1056 Add DNS provider for Servercow.
  .travis.yml
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_servercow.md
  providers/dns/dns_providers.go
  providers/dns/servercow/internal/client.go
  providers/dns/servercow/internal/client_test.go
  providers/dns/servercow/internal/fixtures/records-01.json
  providers/dns/servercow/internal/model.go
  providers/dns/servercow/internal/model_test.go
  providers/dns/servercow/servercow.go
  providers/dns/servercow/servercow.toml
  providers/dns/servercow/servercow_test.go
Labels: area/dnsprovider, enhancement

#1051 Add DNS provider for Constellix
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_constellix.md
  go.mod
  go.sum
  providers/dns/constellix/constellix.go
  providers/dns/constellix/constellix.toml
  providers/dns/constellix/constellix_test.go
  providers/dns/constellix/internal/auth.go
  providers/dns/constellix/internal/auth_test.go
  providers/dns/constellix/internal/client.go
  providers/dns/constellix/internal/domains.go
  providers/dns/constellix/internal/domains_test.go
  providers/dns/constellix/internal/fixtures/domains-01.json
  providers/dns/constellix/internal/fixtures/domains-02.json
  providers/dns/constellix/internal/fixtures/records-01.json
  providers/dns/constellix/internal/fixtures/records-02.json
  providers/dns/constellix/internal/model.go
  providers/dns/constellix/internal/txtrecords.go
  providers/dns/constellix/internal/txtrecords_test.go
  providers/dns/dns_providers.go
Labels: area/dnsprovider, enhancement

#1068 Update akamai lib.
  go.mod
  go.sum
Labels: area/dnsprovider, bug

#1069 Update to go1.14
  .travis.yml
  go.mod
  providers/dns/checkdomain/checkdomain_test.go
  providers/dns/httpreq/httpreq_test.go
  providers/dns/zoneee/zoneee_test.go
Labels: area/infrastructure, enhancement
