Repository go-acme/lego, pull requests merged in 2020-05, with the labels that each got.

#1136 mythicbeasts: Update API base URL for released v2 API
  providers/dns/mythicbeasts/client.go
Labels: area/dnsprovider, enhancement

#1141 autodns: removes TXT records during CleanUp.
  providers/dns/autodns/client.go
Labels: area/dnsprovider, bug

#1143 Add DNS provider for deSEC.io
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_desec.md
  providers/dns/desec/desec.go
  providers/dns/desec/desec.toml
  providers/dns/desec/desec_test.go
  providers/dns/desec/internal/client.go
  providers/dns/desec/internal/client_test.go
  providers/dns/desec/internal/fixtures/add_record.json
  providers/dns/desec/internal/fixtures/get_record.json
  providers/dns/desec/internal/fixtures/update_record.json
  providers/dns/desec/internal/model.go
  providers/dns/dns_providers.go
Labels: area/dnsprovider, enhancement

#1139 update aws sdk
  go.mod
  go.sum
Labels: area/dnsprovider

#1144 Add DNS provider for Netlify.
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_netlify.md
  providers/dns/dns_providers.go
  providers/dns/netlify/internal/client.go
  providers/dns/netlify/internal/client_test.go
  providers/dns/netlify/internal/fixtures/create_record.json
  providers/dns/netlify/internal/fixtures/get_records.json
  providers/dns/netlify/internal/model.go
  providers/dns/netlify/netlify.go
  providers/dns/netlify/netlify.toml
  providers/dns/netlify/netlify_test.go
Labels: area/dnsprovider, enhancement

#1128 Adding Hezner DNS provider
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_hetzner.md
  providers/dns/dns_providers.go
  providers/dns/hetzner/hetzner.go
  providers/dns/hetzner/hetzner.toml
  providers/dns/hetzner/hetzner_test.go
  providers/dns/hetzner/internal/client.go
  providers/dns/hetzner/internal/client_test.go
  providers/dns/hetzner/internal/fixtures/create_txt_record.json
  providers/dns/hetzner/internal/fixtures/get_txt_record.json
  providers/dns/hetzner/internal/fixtures/get_zone_id.json
  providers/dns/hetzner/internal/model.go
Labels: area/dnsprovider, enhancement

#1135 Add DNS provider for LuaDNS
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_luadns.md
  providers/dns/dns_providers.go
  providers/dns/luadns/internal/client.go
  providers/dns/luadns/internal/client_test.go
  providers/dns/luadns/internal/fixtures/create_record.json
  providers/dns/luadns/internal/fixtures/delete_record.json
  providers/dns/luadns/internal/fixtures/list_zones.json
  providers/dns/luadns/internal/model.go
  providers/dns/luadns/luadns.go
  providers/dns/luadns/luadns.toml
  providers/dns/luadns/luadns_test.go
Labels: area/dnsprovider, enhancement

#1148 Upgrade DNSimple client to 0.60.0
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_dnsimple.md
  go.mod
  go.sum
  providers/dns/dnsimple/dnsimple.go
  providers/dns/dnsimple/dnsimple.toml
Labels: area/dnsprovider, enhancement

#1151 fix: review path information.
  cmd/cmd_renew.go
Labels: area/cli, bug

#1157 cli: add hook on the run command.
  cmd/cmd_renew.go
  cmd/cmd_run.go
  cmd/hook.go
  docs/content/usage/cli/_index.md
  docs/content/usage/cli/examples.md
Labels: area/cli, enhancement

#1161 desec: improve error logs.
  providers/dns/desec/desec.go
  providers/dns/desec/internal/client.go
Labels: area/dnsprovider, enhancement

#1162 doc: improved doc about the build from sources.
  CONTRIBUTING.md
  docs/content/installation/_index.md
Labels: area/documentation, enhancement

#1142 Registrar.ResolveAccountByKey: Fix issues found testing with Pebble
  registration/registar.go
  registration/registar_test.go
Labels: area/lib

#1158 Ensure we return a location during account updates
  acme/api/account.go
  e2e/challenges_test.go
  registration/registar.go
Labels: area/lib

#1173 Add DNS provider for ArvanCloud
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_arvancloud.md
  providers/dns/arvancloud/arvancloud.go
  providers/dns/arvancloud/arvancloud.toml
  providers/dns/arvancloud/arvancloud_test.go
  providers/dns/arvancloud/internal/client.go
  providers/dns/arvancloud/internal/client_test.go
  providers/dns/arvancloud/internal/fixtures/create_txt_record.json
  providers/dns/arvancloud/internal/fixtures/get_txt_record.json
  providers/dns/arvancloud/internal/model.go
  providers/dns/dns_providers.go
Labels: area/dnsprovider, enhancement

#1171 Document all AWS credential environment variables
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_route53.md
  providers/dns/route53/route53.toml
Labels: area/dnsprovider, area/documentation

#1176 inwx: Two-Factor-Authentication
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_inwx.md
  go.mod
  go.sum
  providers/dns/inwx/inwx.go
  providers/dns/inwx/inwx.toml
  providers/dns/inwx/inwx_test.go
Labels: area/dnsprovider, enhancement
