Repository go-acme/lego, pull requests merged in 2020-12, with the labels that each got.

#1319 chore: Goodbye Travis. Hello GitHub Action.
  .github/workflows/go-cross.yml
  .github/workflows/main.yml
  .travis.yml
  Makefile
  e2e/loader/loader.go
  platform/wait/wait_test.go
  providers/dns/exec/exec_test.go
  providers/dns/gcloud/googlecloud_test.go
  providers/dns/oraclecloud/oraclecloud_test.go
Labels: area/infrastructure

#1313 doc: remove landing page button.
  docs/config.toml
Labels: area/documentation, bug

#1315 hyperone: Minor tweaks of documentation
  docs/content/dns/zz_gen_hyperone.md
  providers/dns/hyperone/hyperone.toml
Labels: area/dnsprovider, area/documentation, enhancement

#1318 vult, dnspod: fix default HTTP timeout.
  providers/dns/dnspod/dnspod.go
  providers/dns/vultr/vultr.go
Labels: area/dnsprovider, bug

#1296 pdns: get exact zone instead of all zones
  providers/dns/pdns/client.go
Labels: area/dnsprovider, enhancement

#1314 Increase INWX propagation timeout to 360s to improve robustness
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_inwx.md
  providers/dns/inwx/inwx.go
  providers/dns/inwx/inwx.toml
Labels: area/dnsprovider, enhancement

#1321 Example for RFC 2136 provider
  docs/content/dns/zz_gen_rfc2136.md
  providers/dns/rfc2136/rfc2136.toml
Labels: area/dnsprovider, area/documentation

#1324 Add DNS provider for Loopia
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_loopia.md
  go.sum
  providers/dns/dns_providers.go
  providers/dns/loopia/internal/client.go
  providers/dns/loopia/internal/client_test.go
  providers/dns/loopia/internal/mock_test.go
  providers/dns/loopia/internal/types.go
  providers/dns/loopia/loopia.go
  providers/dns/loopia/loopia.toml
  providers/dns/loopia/loopia_mock_test.go
  providers/dns/loopia/loopia_test.go
Labels: area/dnsprovider, enhancement

#1325 chore: update linter.
  .github/workflows/main.yml
  .golangci.toml
  providers/dns/checkdomain/client_test.go
  providers/dns/designate/designate_test.go
  providers/dns/hyperone/internal/client_test.go
  providers/dns/infomaniak/internal/client_test.go
  providers/dns/joker/internal/dmapi/client_test.go
  providers/dns/lightsail/lightsail_test.go
  providers/dns/lightsail/mock_server_test.go
  providers/dns/loopia/internal/client_test.go
  providers/dns/namecheap/namecheap_test.go
  providers/dns/otc/mock_test.go
  providers/dns/route53/mock_test.go
  providers/dns/route53/route53_test.go
Labels: area/infrastructure, enhancement
