Repository go-acme/lego, pull requests merged in 2020-08, with the labels that each got.

#1226 edgsedns: update with init for config
  go.mod
  go.sum
  providers/dns/edgedns/edgedns.go
Labels: area/dnsprovider, enhancement

#1219 designate: add support for Openstack clouds.yaml
  go.mod
  go.sum
  providers/dns/designate/designate.go
  providers/dns/designate/designate_test.go
Labels: area/dnsprovider, enhancement

#1225 azure: allow selecting environments
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_azure.md
  providers/dns/azure/azure.go
  providers/dns/azure/azure.toml
  providers/dns/azure/azure_test.go
Labels: area/dnsprovider, enhancement

#1228 chore: update linter.
  .golangci.toml
  certificate/authorization.go
  challenge/challenges.go
  challenge/dns01/dns_challenge.go
  lego/client_config.go
  providers/dns/conoha/internal/client_test.go
  providers/dns/gandi/gandi.go
  providers/dns/netcup/internal/client_test.go
  providers/dns/netcup/netcup.go
  providers/dns/nifcloud/internal/client.go
  providers/dns/nifcloud/nifcloud.go
Labels: area/infrastructure, enhancement

#1230 Add additional namecheap-specific infos
  docs/content/dns/zz_gen_edgedns.md
  docs/content/dns/zz_gen_namecheap.md
  providers/dns/edgedns/edgedns.toml
  providers/dns/namecheap/namecheap.toml
Labels: area/dnsprovider, area/documentation, enhancement

#1233 Add DNS provider for HyperOne
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_hyperone.md
  providers/dns/dns_providers.go
  providers/dns/hyperone/hyperone.go
  providers/dns/hyperone/hyperone.toml
  providers/dns/hyperone/hyperone_test.go
  providers/dns/hyperone/internal/client.go
  providers/dns/hyperone/internal/client_test.go
  providers/dns/hyperone/internal/fixtures/createRecord.json
  providers/dns/hyperone/internal/fixtures/createRecordset.json
  providers/dns/hyperone/internal/fixtures/invalidPassport.json
  providers/dns/hyperone/internal/fixtures/record.json
  providers/dns/hyperone/internal/fixtures/recordset.json
  providers/dns/hyperone/internal/fixtures/validPassport.json
  providers/dns/hyperone/internal/fixtures/zones.json
  providers/dns/hyperone/internal/models.go
  providers/dns/hyperone/internal/passport.go
  providers/dns/hyperone/internal/passport_test.go
  providers/dns/hyperone/internal/token.go
  providers/dns/hyperone/internal/token_test.go
Labels: area/dnsprovider, enhancement

#1237 desec: applies API rate limits.
  go.mod
  go.sum
  providers/dns/desec/desec.go
  providers/dns/desec/internal/client.go
  providers/dns/desec/internal/client_test.go
  providers/dns/desec/internal/fixtures/add_record.json
  providers/dns/desec/internal/fixtures/get_record.json
  providers/dns/desec/internal/fixtures/update_record.json
  providers/dns/desec/internal/model.go
Labels: area/dnsprovider, bug

#1239 scaleway: fix example
  docs/content/dns/zz_gen_scaleway.md
  providers/dns/scaleway/scaleway.toml
Labels: area/dnsprovider, area/documentation, bug
