Repository go-acme/lego, pull requests merged in 2020-11, with the labels that each got.

#1279 Deprecate OS_TENANT_NAME as required field
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_designate.md
  providers/dns/designate/designate.go
  providers/dns/designate/designate.toml
  providers/dns/designate/designate_test.go
Labels: area/dnsprovider, enhancement

#1283 acme/api: use postAsGet instead of post for AccountService.Get
  acme/api/account.go
  e2e/challenges_test.go
Labels: area/lib, bug

#1291 azure: fix target must be a non-nil pointer
  providers/dns/azure/azure.go
Labels: area/dnsprovider, bug

#1292 otc: select correct zone if multiple returned
  providers/dns/otc/client.go
  providers/dns/otc/mock_test.go
Labels: area/dnsprovider, bug

#1298 fix: preferred chain support.
  acme/api/certificate.go
  acme/api/order.go
  acme/api/order_test.go
  acme/commons.go
  certificate/certificates.go
  certificate/certificates_test.go
Labels: area/lib, bug

#1305 chore: update linter.
  .golangci.toml
  acme/commons.go
  acme/errors.go
  certificate/certificates.go
  platform/config/env/env.go
  providers/dns/acmedns/acmedns.go
  providers/dns/netcup/internal/client.go
Labels: area/infrastructure, enhancement

#1307 azure: fix error handling.
  providers/dns/azure/azure.go
Labels: area/dnsprovider, bug

#1310 Add 'since' tag to HyperOne provider
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_hyperone.md
  providers/dns/hyperone/hyperone.toml
Labels: area/dnsprovider, area/documentation, enhancement

#1302 vultr: Update to govultr v2 API
  go.mod
  go.sum
  providers/dns/vultr/vultr.go
  providers/dns/vultr/vultr_test.go
Labels: area/dnsprovider, enhancement

#1312 pdns: URL request creation.
  providers/dns/pdns/client.go
  providers/dns/pdns/client_test.go
Labels: area/dnsprovider, bug
