Repository go-acme/lego, pull requests merged in 2020-10, with the labels that each got.

#1265 Improve documentation
  docs/content/usage/cli/_index.md
  docs/content/usage/cli/examples.md
Labels: area/documentation, enhancement

#1270 fix: use http.Header.Set method instead of Add.
  acme/api/internal/nonces/nonce_manager_test.go
  acme/api/internal/secure/jws_test.go
  challenge/dns01/nameserver.go
  challenge/http01/http_challenge_server.go
  platform/tester/api.go
  providers/dns/azure/azure.go
  providers/dns/constellix/internal/auth.go
  providers/dns/dynu/internal/auth.go
  providers/dns/dynu/internal/client.go
  providers/dns/internal/selectel/client.go
  providers/dns/mythicbeasts/client.go
  providers/dns/scaleway/internal/client.go
Labels: area/lib, bug

#1275 chore: update linter.
  cmd/certs_storage.go
Labels: area/infrastructure, enhancement

#1277 Add Infomaniak DNS provider
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_infomaniak.md
  providers/dns/dns_providers.go
  providers/dns/infomaniak/infomaniak.go
  providers/dns/infomaniak/infomaniak.toml
  providers/dns/infomaniak/infomaniak_test.go
  providers/dns/infomaniak/internal/client.go
  providers/dns/infomaniak/internal/client_test.go
  providers/dns/infomaniak/internal/models.go
Labels: area/dnsprovider, enhancement

#1278 chore: update linter.
  .golangci.toml
  README.md
  acme/api/account.go
  acme/api/api.go
  challenge/tlsalpn01/tls_alpn_challenge_server.go
  cmd/hook.go
  providers/dns/acmedns/acmedns.go
  providers/dns/azure/azure.go
  providers/dns/cloudflare/cloudflare.go
  providers/dns/edgedns/edgedns.go
  providers/dns/gcloud/googlecloud.go
  providers/dns/inwx/inwx.go
  providers/dns/joker/provider_dmapi.go
  providers/dns/joker/provider_svc.go
  providers/dns/ns1/ns1.go
  providers/dns/pdns/client.go
  providers/dns/sakuracloud/client.go
  providers/dns/yandex/yandex.go
  registration/registar.go
Labels: area/infrastructure, enhancement
