Repository go-acme/lego, pull requests merged in 2021-06, with the labels that each got.

#1420 mythicbeasts: typo in documentation
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_mythicbeasts.md
  providers/dns/mythicbeasts/mythicbeasts.toml
Labels: area/documentation, bug

#1421 mythicbeasts: update API Auth endpoint in documentation
  providers/dns/mythicbeasts/mythicbeasts.toml
Labels: area/documentation, bug

#1419 Add DNS provider for Simply.com
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_simply.md
  providers/dns/dns_providers.go
  providers/dns/infomaniak/internal/client.go
  providers/dns/simply/internal/client.go
  providers/dns/simply/internal/client_test.go
  providers/dns/simply/internal/fixtures/add_record.json
  providers/dns/simply/internal/fixtures/bad_auth_error.json
  providers/dns/simply/internal/fixtures/bad_zone_error.json
  providers/dns/simply/internal/fixtures/get_records.json
  providers/dns/simply/internal/fixtures/invalid_record_id_error.json
  providers/dns/simply/internal/fixtures/success.json
  providers/dns/simply/internal/types.go
  providers/dns/simply/simply.go
  providers/dns/simply/simply.toml
  providers/dns/simply/simply_test.go
Labels: area/dnsprovider, enhancement

#1423 csr: Support the type `NEW CERTIFICATE REQUEST`
  certcrypto/crypto.go
  cmd/setup.go
Labels: area/cli, area/lib, bug

#1424 simply: fix Go doc.
  providers/dns/simply/simply.go
Labels: area/dnsprovider, area/documentation, bug

#1428 lib: fix backoff in SolverManager
  challenge/resolver/solver_manager.go
Labels: area/lib, bug

#1429 lib: use permanent error instead of context cancellation
  acme/api/api.go
  go.mod
  go.sum
  providers/dns/dynu/internal/client.go
  providers/dns/hostingde/client.go
Labels: area/lib, bug

#1431 Add DNS provider for Internet.bs
  .golangci.toml
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_internetbs.md
  providers/dns/dns_providers.go
  providers/dns/internetbs/internal/client.go
  providers/dns/internetbs/internal/client_test.go
  providers/dns/internetbs/internal/fixtures/Domain_DnsRecord_Add_FAILURE.json
  providers/dns/internetbs/internal/fixtures/Domain_DnsRecord_Add_SUCCESS.json
  providers/dns/internetbs/internal/fixtures/Domain_DnsRecord_List_FAILURE.json
  providers/dns/internetbs/internal/fixtures/Domain_DnsRecord_List_SUCCESS.json
  providers/dns/internetbs/internal/fixtures/Domain_DnsRecord_Remove_SUCCESS.json
  providers/dns/internetbs/internal/types.go
  providers/dns/internetbs/internetbs.go
  providers/dns/internetbs/internetbs.toml
  providers/dns/internetbs/internetbs_test.go
Labels: area/dnsprovider, enhancement

#1434 docs: convert issue templates to issue forms.
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/new_dns_provider.md
  .github/ISSUE_TEMPLATE/new_dns_provider.yml
Labels: area/infrastructure, enhancement

#1438 lightsail: wrong Region env var name
  providers/dns/lightsail/lightsail.go
Labels: area/dnsprovider, bug

#1439 aws: detailed credentials
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_lightsail.md
  docs/content/dns/zz_gen_route53.md
  providers/dns/lightsail/lightsail.toml
  providers/dns/route53/route53.toml
Labels: area/dnsprovider, area/documentation, enhancement

#1444 Add DNS provider for all-inkl
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_allinkl.md
  go.mod
  go.sum
  providers/dns/allinkl/allinkl.go
  providers/dns/allinkl/allinkl.toml
  providers/dns/allinkl/allinkl_test.go
  providers/dns/allinkl/internal/client.go
  providers/dns/allinkl/internal/client_test.go
  providers/dns/allinkl/internal/fixtures/add_dns_settings.json
  providers/dns/allinkl/internal/fixtures/add_dns_settings.xml
  providers/dns/allinkl/internal/fixtures/auth.xml
  providers/dns/allinkl/internal/fixtures/auth_fault.xml
  providers/dns/allinkl/internal/fixtures/delete_dns_settings.json
  providers/dns/allinkl/internal/fixtures/delete_dns_settings.xml
  providers/dns/allinkl/internal/fixtures/get_dns_settings.json
  providers/dns/allinkl/internal/fixtures/get_dns_settings.xml
  providers/dns/allinkl/internal/types.go
  providers/dns/allinkl/internal/types_api.go
  providers/dns/allinkl/internal/types_auth.go
  providers/dns/dns_providers.go
Labels: area/dnsprovider, enhancement
