Repository go-acme/lego, pull requests merged in 2021-08, with the labels that each got.

#1454 alidns: support sts token credential
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_alidns.md
  go.mod
  go.sum
  providers/dns/alidns/alidns.go
  providers/dns/alidns/alidns.toml
Labels: enhancement, area/dnsprovider

#1433 azure: zone name as environment variable
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_azure.md
  providers/dns/azure/azure.go
  providers/dns/azure/azure.toml
Labels: enhancement, area/dnsprovider

#1461 chore: update dependencies.
  go.mod
  go.sum
Labels: enhancement, area/infrastructure

#1462 alidns: support ECS instance RAM role
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_alidns.md
  providers/dns/alidns/alidns.go
  providers/dns/alidns/alidns.toml
  providers/dns/alidns/alidns_test.go
Labels: enhancement, area/dnsprovider

#1467 ovh: follow cname
  providers/dns/ovh/ovh.go
Labels: enhancement, area/dnsprovider

#1470 desec: bump to v0.6.0
  go.mod
  go.sum
  providers/dns/desec/desec.go
Labels: area/dnsprovider
