Repository go-acme/lego, pull requests merged in 2021-05, with the labels that each got.

#1396 Add DNS provider for Porkbun
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_porkbun.md
  go.mod
  go.sum
  providers/dns/checkdomain/client_test.go
  providers/dns/dns_providers.go
  providers/dns/porkbun/porkbun.go
  providers/dns/porkbun/porkbun.toml
  providers/dns/porkbun/porkbun_test.go
Labels: area/dnsprovider, enhancement

#1398 hurricane: documentation typo in domain name
  docs/content/dns/zz_gen_hurricane.md
  providers/dns/hurricane/hurricane.toml
Labels: area/documentation, bug

#1403 lib: improve wait.For returns.
  platform/wait/wait.go
  platform/wait/wait_test.go
Labels: area/lib, enhancement

#1402 log: Use stderr instead of stdout.
  log/logger.go
Labels: area/cli, enhancement

#1405 hostingde: autodetection of the zone name.
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_hostingde.md
  providers/dns/hostingde/hostingde.go
  providers/dns/hostingde/hostingde.toml
  providers/dns/hostingde/hostingde_test.go
Labels: area/dnsprovider, enhancement

#1407 lightsail: improve documentation
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_lightsail.md
  providers/dns/lightsail/lightsail.toml
Labels: area/dnsprovider, area/documentation, enhancement

#1409 hurricane: only treat first word of response body as response code
  providers/dns/hurricane/internal/client.go
  providers/dns/hurricane/internal/client_test.go
Labels: area/dnsprovider, bug

#1410 ovh: fix example in documentation
  docs/content/dns/zz_gen_ovh.md
  providers/dns/ovh/ovh.toml
Labels: area/documentation, bug

#1413 Add DNS provider for Infoblox
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_infoblox.md
  go.mod
  go.sum
  providers/dns/dns_providers.go
  providers/dns/infoblox/infoblox.go
  providers/dns/infoblox/infoblox.toml
  providers/dns/infoblox/infoblox_test.go
Labels: area/dnsprovider, enhancement

#1417 hurricane: add API rate limiter.
  go.mod
  go.sum
  providers/dns/hurricane/hurricane.go
  providers/dns/hurricane/internal/client.go
  providers/dns/hurricane/internal/client_test.go
Labels: area/dnsprovider, bug
