Repository go-acme/lego, pull requests merged in 2021-07, with the labels that each got.

#1448 docs: improve issue forms.
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/new_dns_provider.yml
Labels: area/infrastructure, enhancement

#1453 chore: update dependencies
  go.mod
  go.sum
  providers/dns/azure/azure_test.go
  providers/dns/route53/route53.go
Labels: area/infrastructure, enhancement

#1456 Add DNS provider for g-core labs
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_gcore.md
  providers/dns/dns_providers.go
  providers/dns/gcore/gcore.go
  providers/dns/gcore/gcore.toml
  providers/dns/gcore/gcore_test.go
  providers/dns/gcore/internal/client.go
  providers/dns/gcore/internal/client_test.go
  providers/dns/gcore/internal/types.go
Labels: area/dnsprovider, enhancement

#1457 chore: fix github action cache.
  .github/workflows/go-cross.yml
  .github/workflows/main.yml
Labels: area/infrastructure, bug
