Repository go-acme/lego, pull requests merged in 2021-03, with the labels that each got.

#1365 Typo issue in ArvanCloud configuration sample
  docs/content/dns/zz_gen_arvancloud.md
  providers/dns/arvancloud/arvancloud.toml
Labels: area/dnsprovider, area/documentation, bug

#1368 Add issue templates.
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/new_dns_provider.md
Labels: area/infrastructure, enhancement

#1370 chore: update dependencies
  docs/content/dns/zz_gen_dnspod.md
  go.mod
  go.sum
  providers/dns/alidns/alidns.go
  providers/dns/cloudflare/client.go
  providers/dns/cloudflare/cloudflare.go
  providers/dns/ionos/internal/client_test.go
  providers/dns/rfc2136/rfc2136.go
  providers/dns/rfc2136/rfc2136_test.go
  providers/dns/transip/transip_test.go
Labels: area/infrastructure

#1372 exoscale: fix version.
  go.mod
  go.sum
Labels: bug

#1376 make: fix validate-docs
  Makefile
Labels: area/documentation, area/infrastructure

#1374 powerdns: several improvements
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_pdns.md
  providers/dns/pdns/client.go
  providers/dns/pdns/pdns.go
  providers/dns/pdns/pdns.toml
Labels: area/dnsprovider, enhancement

#1379 chore: update linter
  .github/workflows/main.yml
  .golangci.toml
  providers/dns/constellix/internal/model.go
  providers/dns/constellix/internal/txtrecords_test.go
  providers/dns/otc/mock_test.go
Labels: area/infrastructure, enhancement
