Repository go-acme/lego, pull requests merged in 2021-02, with the labels that each got.

#1345 Add Domeneshop DNS01 provider
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_domeneshop.md
  providers/dns/dns_providers.go
  providers/dns/domeneshop/domeneshop.go
  providers/dns/domeneshop/domeneshop.toml
  providers/dns/domeneshop/domeneshop_test.go
  providers/dns/domeneshop/internal/client.go
  providers/dns/domeneshop/internal/client_test.go
  providers/dns/domeneshop/internal/types.go
Labels: area/dnsprovider, enhancement

#1346 chore: update linter.
  .github/workflows/main.yml
  .golangci.toml
Labels: area/infrastructure, enhancement

#1344 Add DNS provider for Hurricane Electric
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_hurricane.md
  providers/dns/dns_providers.go
  providers/dns/hurricane/hurricane.go
  providers/dns/hurricane/hurricane.toml
  providers/dns/hurricane/hurricane_test.go
  providers/dns/hurricane/internal/client.go
  providers/dns/hurricane/internal/client_test.go
Labels: area/dnsprovider, enhancement

#1350 Update for go1.16
  .github/workflows/go-cross.yml
  .github/workflows/main.yml
  CONTRIBUTING.md
  docs/content/installation/_index.md
  go.mod
Labels: area/infrastructure, enhancement

#1348 Add DNS provider for Njalla
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_njalla.md
  providers/dns/dns_providers.go
  providers/dns/njalla/internal/client.go
  providers/dns/njalla/internal/client_test.go
  providers/dns/njalla/internal/types.go
  providers/dns/njalla/njalla.go
  providers/dns/njalla/njalla.toml
  providers/dns/njalla/njalla_test.go
Labels: area/dnsprovider, enhancement

#1340 edgedns: add support for .edgerc file
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_edgedns.md
  providers/dns/edgedns/edgedns.go
  providers/dns/edgedns/edgedns.toml
  providers/dns/edgedns/edgedns_integration_test.go
  providers/dns/edgedns/edgedns_test.go
Labels: area/dnsprovider, enhancement

#1356 doc: Fix typo in env var name in Mythic Beasts usage example
  docs/content/dns/zz_gen_mythicbeasts.md
  providers/dns/mythicbeasts/mythicbeasts.toml
Labels: area/dnsprovider, area/documentation, bug

#1354 dnspod: improve search accuracy when a domain have more than 100 records
  providers/dns/dnspod/dnspod.go
Labels: area/dnsprovider, bug

#1358 mythicbeasts: implement `ProviderTimeout`
  providers/dns/mythicbeasts/mythicbeasts.go
Labels: area/dnsprovider, bug

#1360 designate: support for Openstack Application Credentials
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_designate.md
  go.mod
  go.sum
  providers/dns/designate/designate.go
  providers/dns/designate/designate.toml
  providers/dns/designate/designate_test.go
Labels: area/dnsprovider, enhancement

#1361 desec: fix error with default TTL
  providers/dns/desec/desec.go
Labels: area/dnsprovider, bug

#1331 cloudns: Improve reliability
  providers/dns/cloudns/cloudns.go
  providers/dns/cloudns/internal/client.go
  providers/dns/cloudns/internal/client_test.go
  providers/dns/cloudns/internal/types.go
Labels: area/dnsprovider, enhancement

#1336 Increase HTTP client timeouts
  lego/client_config.go
Labels: area/lib, enhancement
