Repository go-acme/lego, pull requests merged in 2022-09, with the labels that each got.

#1694 Add DNS provider for YandexCloud
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_infoblox.md
  docs/content/dns/zz_gen_yandexcloud.md
  go.mod
  go.sum
  providers/dns/dns_providers.go
  providers/dns/yandexcloud/yandexcloud.go
  providers/dns/yandexcloud/yandexcloud.toml
  providers/dns/yandexcloud/yandexcloud_test.go
Labels: enhancement, area/dnsprovider

#1708 chore: update linter
  .github/workflows/pr.yml
  .golangci.toml
  providers/dns/clouddns/internal/client.go
  providers/dns/cloudns/internal/client.go
  providers/dns/digitalocean/client.go
  providers/dns/dreamhost/client.go
  providers/dns/dyn/client.go
  providers/dns/gandiv5/client.go
  providers/dns/glesys/client.go
  providers/dns/joker/internal/dmapi/client.go
  providers/dns/mydnsjp/client.go
  providers/dns/mythicbeasts/client.go
  providers/dns/namecheap/client.go
  providers/dns/otc/client.go
  providers/dns/safedns/internal/client.go
  providers/dns/vercel/internal/client.go
Labels: enhancement, area/infrastructure

#1706 Add DNS provider for VK Cloud
  .golangci.toml
  README.md
  cmd/account.go
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_vkcloud.md
  providers/dns/dns_providers.go
  providers/dns/vkcloud/internal/client.go
  providers/dns/vkcloud/internal/types.go
  providers/dns/vkcloud/vkcloud.go
  providers/dns/vkcloud/vkcloud.toml
  providers/dns/vkcloud/vkcloud_test.go
Labels: enhancement, area/dnsprovider, contrib/waiting-for-feedback

#1709 chore: update dependencies
  go.mod
  go.sum
  providers/dns/linode/linode_test.go
Labels: enhancement, area/infrastructure

#1711 docs: fix typo
  registration/registar.go
Labels: bug, area/documentation

#1707 Add DNS provider for CIVO
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_civo.md
  go.mod
  go.sum
  providers/dns/civo/civo.go
  providers/dns/civo/civo.toml
  providers/dns/civo/civo_test.go
  providers/dns/dns_providers.go
Labels: enhancement, area/dnsprovider

#1715 feat: deprecate Yandex and DNSPod
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_dnspod.md
  docs/content/dns/zz_gen_yandex.md
  providers/dns/dnspod/dnspod.toml
  providers/dns/yandex/yandex.toml
Labels: enhancement, area/dnsprovider, area/documentation

#1716 lightsail: cleanup
  providers/dns/lightsail/lightsail.go
Labels: enhancement, area/dnsprovider

#1677 add recursive CNAME lookup support
  challenge/dns01/dns_challenge.go
Labels: enhancement, area/lib, area/cname

#1713 allinkl: removed deprecated sha1 hashing
  providers/dns/allinkl/internal/client.go
Labels: enhancement, area/dnsprovider

#1679 pdns: notify secondary servers after updates
  providers/dns/pdns/client.go
  providers/dns/pdns/pdns.go
Labels: enhancement, area/dnsprovider

#1673 gcloud: update golang.org/x/oauth2
  go.mod
  go.sum
Labels: enhancement, area/dnsprovider

#1655 Remove embedded issuer certificates from issued certificate if bundle is false
  acme/api/certificate.go
  certificate/certificates_test.go
Labels: enhancement, area/lib

#1717 luadns: fix cname support
  acme/api/internal/nonces/nonce_manager_test.go
  acme/api/internal/secure/jws_test.go
  providers/dns/luadns/luadns.go
Labels: bug, area/dnsprovider

#1718 feat: take out CNAME support from experimental features
  .golangci.toml
  challenge/dns01/dns_challenge.go
  challenge/dns01/nameserver.go
  challenge/dns01/nameserver_unix.go
  challenge/dns01/nameserver_windows.go
  docs/content/dns/_index.md
  providers/dns/acmedns/acmedns_test.go
  providers/dns/versio/versio_test.go
Labels: enhancement, area/cname

#1719 docs: un-deprecate Yandex
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_yandex.md
  providers/dns/yandex/yandex.toml
Labels: enhancement, area/dnsprovider, area/documentation
