Repository go-acme/lego, pull requests merged in 2022-12, with the labels that each got.

#1778 fix: return an error when extracting record name
  providers/dns/allinkl/allinkl.go
  providers/dns/azure/azure.go
  providers/dns/azure/private.go
  providers/dns/azure/public.go
  providers/dns/cloudns/internal/client.go
  providers/dns/cloudns/internal/client_test.go
  providers/dns/cloudxns/internal/client.go
  providers/dns/domeneshop/domeneshop.go
  providers/dns/dynu/dynu.go
  providers/dns/epik/epik.go
  providers/dns/freemyip/freemyip.go
  providers/dns/hosttech/hosttech.go
  providers/dns/joker/provider_dmapi.go
  providers/dns/joker/provider_svc.go
  providers/dns/liara/liara.go
  providers/dns/linode/linode.go
  providers/dns/loopia/loopia.go
  providers/dns/loopia/loopia_test.go
  providers/dns/ns1/ns1.go
  providers/dns/porkbun/porkbun.go
  providers/dns/regru/regru.go
  providers/dns/simply/simply.go
  providers/dns/transip/transip.go
  providers/dns/variomedia/variomedia.go
  providers/dns/vegadns/vegadns.go
  providers/dns/vinyldns/vinyldns.go
  providers/dns/wedos/wedos.go
Labels: bug, area/dnsprovider

#1779 ibmcloud: add support for subdomains
  providers/dns/ibmcloud/internal/wrapper.go
Labels: enhancement, area/dnsprovider

#1784 chore: upgrade actions
  .github/workflows/documentation.yml
  .github/workflows/go-cross.yml
  .github/workflows/pr.yml
  .github/workflows/release.yml
Labels: enhancement, area/infrastructure

#1788 tencentcloud: support punycode domain
  providers/dns/tencentcloud/client.go
Labels: bug, area/dnsprovider

#1790 infomaniak: CNAME support
  providers/dns/infomaniak/infomaniak.go
Labels: bug, area/dnsprovider
