Repository go-acme/lego, pull requests merged in 2022-02, with the labels that each got.

#1588 Add DNS provider for iwantmyname
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_iwantmyname.md
  providers/dns/dns_providers.go
  providers/dns/iwantmyname/internal/client.go
  providers/dns/iwantmyname/internal/client_test.go
  providers/dns/iwantmyname/iwantmyname.go
  providers/dns/iwantmyname/iwantmyname.toml
  providers/dns/iwantmyname/iwantmyname_test.go
Labels: enhancement, area/dnsprovider

#1595 docs: fix typos for usage hostingde example
  docs/content/dns/zz_gen_hostingde.md
  providers/dns/hostingde/hostingde.toml
Labels: bug, area/documentation

#1596 Fix panic in certcrypto.ParsePEMPrivateKey
  certcrypto/crypto.go
  certcrypto/crypto_test.go
Labels: bug, area/lib

#1602 docs: fix link in the httpreq page
  docs/content/dns/zz_gen_httpreq.md
  providers/dns/httpreq/httpreq.toml
Labels: bug, area/dnsprovider, area/documentation
