Repository go-acme/lego, pull requests merged in 2022-10, with the labels that each got.

#1687 digitalocean: configurable base URL
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_digitalocean.md
  docs/content/dns/zz_gen_yandex.md
  providers/dns/digitalocean/digitalocean.go
  providers/dns/digitalocean/digitalocean.toml
Labels: enhancement, area/dnsprovider

#1731 oraclecloud: use fqdn to resolve zone
  providers/dns/oraclecloud/oraclecloud.go
Labels: bug, area/dnsprovider, area/cname

#1732 duckdns: fix CNAME support
  CHANGELOG.md
  providers/dns/duckdns/duckdns.go
  providers/dns/duckdns/duckdns_test.go
Labels: bug, area/dnsprovider, area/cname

#1733 cname: stop trying to traverse cname if none have been found
  challenge/dns01/dns_challenge.go
Labels: bug, area/lib, area/cname

#1727 Route 53: Update IAM policy example to grant least privilege access
  docs/content/dns/zz_gen_route53.md
  providers/dns/route53/route53.toml
Labels: enhancement, area/dnsprovider, area/documentation
