Repository go-acme/lego, pull requests merged in 2022-04, with the labels that each got.

#1616 tencentcloud: fix InvalidParameter.DomainInvalid error when using DNS challenges
  providers/dns/tencentcloud/client.go
Labels: bug, area/dnsprovider

#1627 bluecat: rewrite provider implementation
  docs/content/dns/zz_gen_bluecat.md
  providers/dns/bluecat/bluecat.go
  providers/dns/bluecat/bluecat.toml
  providers/dns/bluecat/client.go
  providers/dns/bluecat/internal/client.go
  providers/dns/bluecat/internal/client_test.go
  providers/dns/bluecat/internal/types.go
Labels: enhancement, area/dnsprovider

#1630 dnsimple: add debug option
  providers/dns/dnsimple/dnsimple.go
Labels: enhancement, area/dnsprovider

#1629 gcore: change dns api url
  providers/dns/gcore/internal/client.go
Labels: enhancement, area/dnsprovider

#1633 rfc2136: fix TSIG secret
  Makefile
  providers/dns/rfc2136/rfc2136.go
Labels: bug, area/dnsprovider

#1636 chore: update CI
  .github/workflows/documentation.yml
  .github/workflows/go-cross.yml
  .github/workflows/pr.yml
  .github/workflows/release.yml
  go.mod
Labels: enhancement, area/infrastructure

#1635 Add Vercel DNS provider
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_vercel.md
  providers/dns/dns_providers.go
  providers/dns/vercel/internal/client.go
  providers/dns/vercel/internal/client_test.go
  providers/dns/vercel/internal/types.go
  providers/dns/vercel/vercel.go
  providers/dns/vercel/vercel.toml
  providers/dns/vercel/vercel_test.go
Labels: enhancement, area/dnsprovider
