Repository go-acme/lego, pull requests merged in 2023-04, with the labels that each got.

#1884 docs: Add ArchLinux package, fix AUR link
  docs/content/installation/_index.md
Labels: enhancement, area/documentation

#1883 ultradns: update link
  docs/content/dns/zz_gen_ultradns.md
  providers/dns/ultradns/ultradns.toml
Labels: enhancement, area/dnsprovider, area/documentation

#1894 rimuhosting: fix API base URL
  providers/dns/internal/rimuhosting/client.go
Labels: bug, area/dnsprovider

#1890 Add Brandit.com as DNS provider
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_brandit.md
  docs/data/zz_cli_help.toml
  providers/dns/brandit/brandit.go
  providers/dns/brandit/brandit.toml
  providers/dns/brandit/brandit_test.go
  providers/dns/brandit/internal/client.go
  providers/dns/brandit/internal/client_test.go
  providers/dns/brandit/internal/fixtures/add-record.json
  providers/dns/brandit/internal/fixtures/delete-record.json
  providers/dns/brandit/internal/fixtures/list-records.json
  providers/dns/brandit/internal/fixtures/status-domain.json
  providers/dns/brandit/internal/types.go
  providers/dns/dns_providers.go
Labels: enhancement, area/dnsprovider
