Repository go-acme/lego, pull requests merged in 2023-07, with the labels that each got.

#1945 Add DNS provider for Efficient IP
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_efficientip.md
  docs/data/zz_cli_help.toml
  providers/dns/dns_providers.go
  providers/dns/efficientip/efficientip.go
  providers/dns/efficientip/efficientip.toml
  providers/dns/efficientip/efficientip_test.go
  providers/dns/efficientip/internal/client.go
  providers/dns/efficientip/internal/client_test.go
  providers/dns/efficientip/internal/fixtures/dns_rr_add.json
  providers/dns/efficientip/internal/fixtures/dns_rr_delete-error.json
  providers/dns/efficientip/internal/fixtures/dns_rr_delete.json
  providers/dns/efficientip/internal/fixtures/dns_rr_info.json
  providers/dns/efficientip/internal/fixtures/dns_rr_list.json
  providers/dns/efficientip/internal/types.go
Labels: enhancement, area/dnsprovider

#1830 azure: new implementation based on the new API client
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_azure.md
  docs/content/dns/zz_gen_azuredns.md
  docs/data/zz_cli_help.toml
  go.mod
  go.sum
  providers/dns/azure/azure.go
  providers/dns/azure/azure.toml
  providers/dns/azure/private.go
  providers/dns/azure/public.go
  providers/dns/azuredns/azuredns.go
  providers/dns/azuredns/azuredns.toml
  providers/dns/azuredns/azuredns_test.go
  providers/dns/azuredns/private.go
  providers/dns/azuredns/public.go
  providers/dns/dns_providers.go
Labels: enhancement, area/dnsprovider

#1952 Add Metaname.net as DNS provider
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_metaname.md
  docs/data/zz_cli_help.toml
  go.mod
  go.sum
  providers/dns/dns_providers.go
  providers/dns/metaname/metaname.go
  providers/dns/metaname/metaname.toml
  providers/dns/metaname/metaname_test.go
Labels: enhancement, area/dnsprovider

#1956 fix: ensure case-insensitive comparison of CNAME records
  challenge/dns01/cname.go
  challenge/dns01/cname_test.go
Labels: bug, area/dnsprovider, area/cname

#1954 Add IPv64 as DNS Provider
  .golangci.yml
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_ipv64.md
  docs/data/zz_cli_help.toml
  providers/dns/dns_providers.go
  providers/dns/ipv64/internal/client.go
  providers/dns/ipv64/internal/client_test.go
  providers/dns/ipv64/internal/fixtures/add_record-error.json
  providers/dns/ipv64/internal/fixtures/add_record.json
  providers/dns/ipv64/internal/fixtures/del_record-error.json
  providers/dns/ipv64/internal/fixtures/del_record.json
  providers/dns/ipv64/internal/fixtures/error.json
  providers/dns/ipv64/internal/fixtures/get_domains.json
  providers/dns/ipv64/internal/types.go
  providers/dns/ipv64/ipv64.go
  providers/dns/ipv64/ipv64.toml
  providers/dns/ipv64/ipv64_test.go
Labels: enhancement, area/dnsprovider

#1843 Experimental option to force DNS queries to use TCP
  challenge/dns01/nameserver.go
Labels: enhancement, area/lib

#1964 servercow: fix regression
  providers/dns/servercow/internal/client.go
Labels: bug, area/dnsprovider

#1971 gcore: change API domain
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_gcore.md
  providers/dns/gcore/gcore.go
  providers/dns/gcore/gcore.toml
  providers/dns/gcore/internal/client.go
Labels: bug, area/dnsprovider, area/documentation

#1972 azure: fix configuration from env vars
  providers/dns/azuredns/azuredns.go
Labels: bug, area/dnsprovider

#1973 chore: migrate to aws-sdk-go-v2 (lightsail, route53)
  docs/content/dns/zz_gen_lightsail.md
  docs/content/dns/zz_gen_route53.md
  go.mod
  go.sum
  platform/tester/env.go
  platform/tester/env_test.go
  providers/dns/lightsail/lightsail.go
  providers/dns/lightsail/lightsail.toml
  providers/dns/lightsail/lightsail_integration_test.go
  providers/dns/lightsail/lightsail_test.go
  providers/dns/route53/route53.go
  providers/dns/route53/route53.toml
  providers/dns/route53/route53_integration_test.go
  providers/dns/route53/route53_test.go
Labels: enhancement, area/dnsprovider

#1970 Adding S3 support for HTTP domain validation
  .golangci.yml
  cmd/flags.go
  cmd/setup_challenges.go
  docs/data/zz_cli_help.toml
  go.mod
  go.sum
  providers/http/s3/s3.go
  providers/http/s3/s3.toml
  providers/http/s3/s3_test.go
Labels: enhancement, area/httpprovider

#1968 Add DNS provider for cloud.ru
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_cloudru.md
  docs/data/zz_cli_help.toml
  providers/dns/cloudru/cloudru.go
  providers/dns/cloudru/cloudru.toml
  providers/dns/cloudru/cloudru_test.go
  providers/dns/cloudru/internal/client.go
  providers/dns/cloudru/internal/client_test.go
  providers/dns/cloudru/internal/fixtures/auth-error.json
  providers/dns/cloudru/internal/fixtures/auth.json
  providers/dns/cloudru/internal/fixtures/record.json
  providers/dns/cloudru/internal/fixtures/records.json
  providers/dns/cloudru/internal/fixtures/zones.json
  providers/dns/cloudru/internal/identity.go
  providers/dns/cloudru/internal/identity_test.go
  providers/dns/cloudru/internal/types.go
  providers/dns/dns_providers.go
  providers/dns/mythicbeasts/internal/client.go
Labels: enhancement, area/dnsprovider

#1959 Allow to set EAB kid and hmac via environment variables
  cmd/flags.go
  docs/data/zz_cli_help.toml
Labels: enhancement, area/dnsprovider, area/cli

#1976 route53: avoid unexpected records deletion
  providers/dns/route53/route53.go
Labels: bug, area/dnsprovider
