Repository go-acme/lego, pull requests merged in 2023-05, with the labels that each got.

#1908 doc: fix wrong env var name
  docs/content/usage/cli/Obtain-a-Certificate.md
Labels: bug, area/documentation

#1907 feat: add LEGO_CERT_PEM_PATH and LEGO_CERT_PFX_PATH to run hook
  cmd/cmd_run.go
Labels: enhancement, area/cli

#1911 docs: fix `gdomains`→`googledomains`
  docs/content/dns/zz_gen_googledomains.md
  providers/dns/googledomains/googledomains.toml
Labels: area/dnsprovider, area/documentation

#1909 Add DNS provider for Derak Cloud
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_derak.md
  docs/data/zz_cli_help.toml
  providers/dns/derak/derak.go
  providers/dns/derak/derak.toml
  providers/dns/derak/derak_test.go
  providers/dns/derak/internal/client.go
  providers/dns/derak/internal/client_test.go
  providers/dns/derak/internal/fixtures/error.json
  providers/dns/derak/internal/fixtures/record-DELETE.json
  providers/dns/derak/internal/fixtures/record-GET.json
  providers/dns/derak/internal/fixtures/record-PATCH.json
  providers/dns/derak/internal/fixtures/record-PUT.json
  providers/dns/derak/internal/fixtures/records-GET.json
  providers/dns/derak/internal/fixtures/service-cdn-zones.json
  providers/dns/derak/internal/readme.md
  providers/dns/derak/internal/types.go
  providers/dns/dns_providers.go
Labels: enhancement, area/dnsprovider

#1874 fix: archive only domain-related files on revoke
  cmd/certs_storage.go
  cmd/certs_storage_test.go
Labels: bug, area/cli

#1916 route53: minor correction to documentation
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_route53.md
  providers/dns/route53/route53.toml
Labels: bug, area/dnsprovider, area/documentation

#1920 docs: add homebrew installation
  docs/content/installation/_index.md
Labels: enhancement, area/documentation

#1923 autodns: fixes wrong zone in api call if CNAME is used
  providers/dns/autodns/autodns.go
Labels: enhancement, area/dnsprovider

#1918 route53: pass ExternalID property to STS:AssumeRole API operation
  providers/dns/route53/route53.go
  providers/dns/route53/route53.toml
Labels: enhancement, area/dnsprovider

#1924 websupport: simplify errors
  providers/dns/websupport/websupport.go
Labels: enhancement, area/dnsprovider

#1912 Initial ACME Renewal Info (ARI) Implementation
  .golangci.yml
  acme/api/renewal.go
  acme/commons.go
  certificate/renewal.go
  certificate/renewal_test.go
  cmd/cmd_renew.go
  platform/tester/api.go
Labels: enhancement, area/lib, area/cli

#1925 feat: support custom duration for certificate
  acme/api/order.go
  acme/api/order_test.go
  certificate/certificates.go
  cmd/cmd_renew.go
  cmd/cmd_run.go
  cmd/flags.go
  docs/data/zz_cli_help.toml
  e2e/challenges_test.go
Labels: enhancement, area/lib, area/cli
