Repository go-acme/lego, pull requests merged in 2023-03, with the labels that each got.

#1856 feat: add RSA 3072
  certcrypto/crypto.go
  cmd/flags.go
  cmd/setup.go
  docs/data/zz_cli_help.toml
Labels: enhancement, area/lib, area/cli

#1857 chore: update Pebble
  .github/workflows/pr.yml
  e2e/readme.md
Labels: enhancement, area/infrastructure

#1859 docs: --pem and --pfx text disambiguation
  cmd/flags.go
  docs/data/zz_cli_help.toml
Labels: enhancement, area/cli, area/documentation

#1860 docs: --help text fixes
  cmd/flags.go
  docs/data/zz_cli_help.toml
Labels: enhancement, area/cli, area/documentation

#1866 gcloud: update google APIs to latest version
  go.mod
  go.sum
  providers/dns/gcloud/googlecloud_test.go
Labels: enhancement, area/dnsprovider

#1839 Add Google Domains as DNS provider
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_googledomains.md
  docs/data/zz_cli_help.toml
  providers/dns/dns_providers.go
  providers/dns/googledomains/googledomains.go
  providers/dns/googledomains/googledomains.toml
  providers/dns/googledomains/googledomains_test.go
Labels: enhancement, area/dnsprovider

#1871 docs: update dnshomede API documentation
  providers/dns/dnshomede/internal/readme.md
Labels: area/dnsprovider, area/documentation
