Repository go-acme/lego, pull requests merged in 2023-06, with the labels that each got.

#1927 chore: update linter
  .github/workflows/pr.yml
  .golangci.yml
  acme/api/api.go
Labels: enhancement, area/infrastructure

#1936 docs: remove wrong timeout documentation for exec
  docs/content/dns/zz_gen_exec.md
  docs/data/zz_cli_help.toml
  providers/dns/exec/exec.toml
Labels: area/dnsprovider, area/documentation

#1937 fix: read status code from response
  acme/api/internal/sender/sender.go
Labels: bug, area/lib

#1939 dnsmadeeasy: fix DeleteRecord
  providers/dns/dnsmadeeasy/internal/client.go
Labels: bug, area/dnsprovider

#1943 fix: list command
  cmd/cmd_list.go
Labels: bug, area/cli

#1944 fix: ARI explanationURL
  acme/commons.go
Labels: bug, area/lib

#1948 chore: update dependencies
  docs/data/zz_cli_help.toml
  go.mod
  go.sum
  providers/dns/arvancloud/arvancloud.go
  providers/dns/bunny/bunny.go
  providers/dns/gcore/gcore.go
  providers/dns/godaddy/godaddy.go
  providers/dns/hetzner/hetzner.go
  providers/dns/linode/linode.go
  providers/dns/pdns/pdns.go
  providers/dns/rfc2136/rfc2136.go
  providers/dns/transip/fakeclient_test.go
Labels: enhancement, area/infrastructure

#1931 cloudflare: update api client to v0.70.0
  go.mod
  go.sum
  providers/dns/cloudflare/cloudflare.go
  providers/dns/cloudflare/wrapper.go
Labels: enhancement, area/dnsprovider

#1947 Add DNS provider for RcodeZero
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_rcodezero.md
  docs/data/zz_cli_help.toml
  providers/dns/dns_providers.go
  providers/dns/rcodezero/internal/client.go
  providers/dns/rcodezero/internal/client_test.go
  providers/dns/rcodezero/internal/fixtures/error.json
  providers/dns/rcodezero/internal/fixtures/rrsets-response.json
  providers/dns/rcodezero/internal/types.go
  providers/dns/rcodezero/rcodezero.go
  providers/dns/rcodezero/rcodezero.toml
  providers/dns/rcodezero/rcodezero_test.go
Labels: enhancement, area/dnsprovider
