Repository go-acme/lego, pull requests merged in 2023-01, with the labels that each got.

#1796 luadns: removed dot suffix from authzone while searching for zone
  providers/dns/luadns/luadns.go
Labels: bug, area/dnsprovider

#1797 update go-jose package to latest
  acme/api/internal/secure/jws.go
  acme/api/order_test.go
  challenge/resolver/solver_manager_test.go
  go.mod
  go.sum
  providers/dns/hyperone/internal/token.go
Labels: enhancement

#1799 hurricane: fix typo in example command
  docs/content/dns/zz_gen_hurricane.md
  providers/dns/hurricane/hurricane.toml
Labels: bug, area/documentation

#1803 doc: fix cron schedule in example
  docs/content/usage/cli/Renew-a-Certificate.md
Labels: bug, area/documentation

#1785 docs: generate CLI help
  .golangci.toml
  Makefile
  cmd/cmd_dnshelp.go
  cmd/cmd_renew.go
  cmd/cmd_revoke.go
  cmd/cmd_run.go
  cmd/flags.go
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/usage/cli/Options.md
  docs/data/zz_cli_help.toml
  docs/layouts/shortcodes/clihelp.html
  internal/dnsdocs/cli_help/generator.go
  internal/dnsdocs/dns.go.tmpl
Labels: enhancement, area/documentation

#1781 pdns: fix usage of notify only when zone kind is Master or Slave
  providers/dns/pdns/client.go
  providers/dns/pdns/pdns.go
Labels: bug, area/dnsprovider

#1806 Add DNS provider for UltraDNS
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_ultradns.md
  docs/data/zz_cli_help.toml
  go.mod
  go.sum
  providers/dns/dns_providers.go
  providers/dns/ultradns/ultradns.go
  providers/dns/ultradns/ultradns.toml
  providers/dns/ultradns/ultradns_test.go
Labels: enhancement, area/dnsprovider

#1786 docs: expand description for --dns.resolvers
  cmd/flags.go
  docs/content/usage/cli/Options.md
  docs/data/zz_cli_help.toml
Labels: enhancement, area/documentation

#1746 route53: Allow static credentials to be supplied
  providers/dns/route53/route53.go
  providers/dns/route53/route53_test.go
Labels: enhancement, area/dnsprovider

#1808 gcloud: add CLI example
  docs/content/dns/zz_gen_gcloud.md
  providers/dns/gcloud/gcloud.toml
Labels: enhancement, area/dnsprovider, area/documentation

#1815 hetzner: improve zone ID detection
  providers/dns/hetzner/internal/client.go
  providers/dns/hetzner/internal/types.go
Labels: bug, area/dnsprovider

#1821 Add DNS provider for dnsHome.de
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_dnshomede.md
  docs/data/zz_cli_help.toml
  providers/dns/dns_providers.go
  providers/dns/dnshomede/dnshomede.go
  providers/dns/dnshomede/dnshomede.toml
  providers/dns/dnshomede/dnshomede_test.go
  providers/dns/dnshomede/internal/client.go
  providers/dns/dnshomede/internal/client_test.go
  providers/dns/dnshomede/internal/readme.md
Labels: enhancement, area/dnsprovider
