Repository go-acme/lego, pull requests merged in 2023-08, with the labels that each got.

#1983 pdns: fix notify
  providers/dns/pdns/internal/client.go
Labels: bug, area/dnsprovider

#1985 chore: exclude egoscale v1.19.0
  go.mod
Labels: enhancement, area/infrastructure

#1988 azuredns: update docs
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_azuredns.md
  providers/dns/azuredns/azuredns.toml
Labels: enhancement, area/dnsprovider, area/documentation

#1991 exec: fix CLI documention
  docs/content/dns/zz_gen_exec.md
  providers/dns/exec/exec.toml
Labels: bug, area/dnsprovider, area/documentation

#1996 doc: bump hugo version
  .github/workflows/documentation.yml
  .github/workflows/pr.yml
  docs/hugo.toml
Labels: enhancement, area/documentation, area/infrastructure

#1993 chore: update to go1.20
  .github/workflows/documentation.yml
  .github/workflows/go-cross.yml
  .github/workflows/pr.yml
  .github/workflows/release.yml
  certificate/authorization.go
  certificate/certificates.go
  certificate/errors.go
  certificate/errors_test.go
  go.mod
  providers/dns/allinkl/internal/types_api.go
  providers/dns/ipv64/internal/client.go
  providers/dns/ipv64/internal/client_test.go
  providers/dns/ipv64/ipv64.go
Labels: enhancement, area/infrastructure

#1997 doc: fix broken links
  docs/content/dns/zz_gen_edgedns.md
  docs/content/installation/_index.md
  providers/dns/edgedns/edgedns.toml
Labels: bug, area/documentation, contrib/waiting-for-correction

#1994 doc: retrieve hugo-theme-learn as hugo module
  docs/Makefile
  docs/go.mod
  docs/go.sum
  docs/hugo.toml
Labels: enhancement, area/documentation, area/infrastructure

#1999 nearlyfreespeech: fix authentication
  providers/dns/nearlyfreespeech/internal/client.go
  providers/dns/nearlyfreespeech/internal/client_test.go
Labels: bug, area/dnsprovider

#2003 Revert "chore: exclude egoscale v1.19.0"
  go.mod
Labels: bug, area/cli, area/infrastructure
