Repository go-acme/lego, pull requests merged in 2023-10, with the labels that each got.

#2026 azuredns: provide the ability to select authentication methods
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_azuredns.md
  providers/dns/azuredns/azuredns.go
  providers/dns/azuredns/azuredns.toml
Labels: enhancement, area/dnsprovider

#2029 gandiv5: Add "Bearer" prefix to the auth header
  providers/dns/gandiv5/gandiv5_test.go
  providers/dns/gandiv5/internal/client.go
Labels: bug, area/dnsprovider

#2031 liquidweb: detect zone automatically
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_liquidweb.md
  go.mod
  go.sum
  providers/dns/liquidweb/liquidweb.go
  providers/dns/liquidweb/liquidweb.toml
  providers/dns/liquidweb/liquidweb_test.go
  providers/dns/liquidweb/servermock_test.go
Labels: enhancement, area/dnsprovider

#2034 liquidweb: add LWAPI_ prefix for env vars
  platform/config/env/env.go
  platform/config/env/env_test.go
  providers/dns/liquidweb/liquidweb.go
  providers/dns/liquidweb/liquidweb.toml
Labels: enhancement, area/dnsprovider

#2039 nifcloud: fix API requests
  providers/dns/nifcloud/internal/client.go
Labels: bug, area/dnsprovider

#2036 azuredns: allow oidc authentication
  docs/content/dns/zz_gen_azuredns.md
  providers/dns/azuredns/azuredns.go
  providers/dns/azuredns/azuredns.toml
  providers/dns/azuredns/oidc.go
Labels: enhancement, area/dnsprovider

#2046 chore: update linter
  .github/workflows/pr.yml
  .golangci.yml
  certificate/errors_test.go
  challenge/dns01/dns_challenge_manual_test.go
  challenge/tlsalpn01/tls_alpn_challenge_test.go
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_liquidweb.md
  providers/dns/acmedns/acmedns.go
  providers/dns/autodns/autodns_test.go
  providers/dns/brandit/internal/client.go
  providers/dns/checkdomain/checkdomain_test.go
  providers/dns/dns_providers_test.go
  providers/dns/dreamhost/dreamhost_test.go
  providers/dns/edgedns/edgedns_integration_test.go
  providers/dns/epik/internal/client_test.go
  providers/dns/gcloud/googlecloud_test.go
  providers/dns/internal/selectel/client_test.go
  providers/dns/joker/internal/dmapi/client_test.go
  providers/dns/liquidweb/liquidweb_test.go
  providers/dns/loopia/internal/client_test.go
  providers/dns/mydnsjp/mydnsjp_test.go
  providers/dns/namecheap/internal/client.go
  providers/dns/namesilo/namesilo_test.go
  providers/dns/netcup/internal/client_test.go
  providers/dns/otc/internal/mock.go
  providers/dns/otc/otc_test.go
  providers/dns/rackspace/rackspace_test.go
  providers/dns/sakuracloud/wrapper_test.go
  providers/dns/simply/internal/client.go
  providers/dns/sonic/sonic_test.go
  providers/dns/transip/transip_test.go
  providers/dns/ultradns/ultradns_test.go
  providers/dns/vegadns/vegadns_test.go
  providers/dns/wedos/internal/token.go
  providers/dns/yandexcloud/yandexcloud.go
  providers/http/memcached/memcached_test.go
  providers/http/s3/s3_test.go
  registration/registar.go
Labels: enhancement, area/infrastructure
