Repository go-acme/lego, pull requests merged in 2024-07, with the labels that each got.

#2204 designate: allow manually overwriting DNS zone
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_designate.md
  providers/dns/designate/designate.go
  providers/dns/designate/designate.toml
Labels: enhancement, area/dnsprovider

#2230 bluecat: skip deploy
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_bluecat.md
  providers/dns/bluecat/bluecat.go
  providers/dns/bluecat/bluecat.toml
Labels: enhancement, area/dnsprovider

#2225 Add DNS provider for DirectAdmin
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_directadmin.md
  docs/data/zz_cli_help.toml
  providers/dns/directadmin/directadmin.go
  providers/dns/directadmin/directadmin.toml
  providers/dns/directadmin/directadmin_test.go
  providers/dns/directadmin/internal/client.go
  providers/dns/directadmin/internal/client_test.go
  providers/dns/directadmin/internal/types.go
  providers/dns/dns_providers.go
Labels: enhancement, area/dnsprovider

#2232 chore: homogenous zone name env var management
  providers/dns/azure/azure.go
  providers/dns/azure/private.go
  providers/dns/azure/public.go
  providers/dns/azuredns/azuredns.go
  providers/dns/azuredns/private.go
  providers/dns/azuredns/public.go
  providers/dns/bunny/bunny.go
  providers/dns/desec/desec.go
  providers/dns/designate/designate.go
  providers/dns/digitalocean/digitalocean.go
  providers/dns/directadmin/directadmin.go
  providers/dns/hostingde/hostingde.go
  providers/dns/httpnet/httpnet.go
  providers/dns/ovh/ovh.go
  providers/dns/servercow/servercow.go
  providers/dns/zoneee/zoneee.go
Labels: enhancement, area/dnsprovider

#2235 chore: bump to github.com/vultr/govultr/v3
  go.mod
  go.sum
  providers/dns/vultr/vultr.go
  providers/dns/vultr/vultr_test.go
Labels: area/dnsprovider, area/infrastructure

#2234 feat: add LEGO_ISSUER_CERT_PATH to run hook
  cmd/cmd_run.go
Labels: enhancement, area/cli
