Repository go-acme/lego, pull requests merged in 2024-12, with the labels that each got.

#2369 fix(cli): clone the transport with tls-skip-verify
  cmd/setup.go
Labels: bug, area/cli

#2371 infomaniak: increase default propagation timeout
  providers/dns/infomaniak/infomaniak.go
Labels: bug, area/dnsprovider

#2372 fix(cli): create client only when needed
  .golangci.yml
  cmd/cmd_renew.go
  cmd/cmd_revoke.go
  cmd/cmd_run.go
  cmd/setup.go
Labels: bug, area/cli

#2373 inwx: delete only the TXT record related to the DNS challenge
  providers/dns/inwx/inwx.go
Labels: bug, area/dnsprovider

#2376 chore: shared deref and pointer functions
  providers/dns/azuredns/azuredns.go
  providers/dns/azuredns/private.go
  providers/dns/azuredns/public.go
  providers/dns/azuredns/servicediscovery.go
  providers/dns/bunny/bunny.go
  providers/dns/bunny/bunny_test.go
  providers/dns/huaweicloud/huaweicloud.go
  providers/dns/internal/ptr/types.go
  providers/dns/inwx/inwx.go
  providers/dns/lightsail/lightsail_integration_test.go
  providers/dns/route53/route53.go
  providers/dns/route53/route53_integration_test.go
  providers/dns/volcengine/volcengine.go
Labels: enhancement, area/infrastructure

#2368 fix(cli): use retryable client for ACME server calls
  cmd/setup.go
Labels: bug, area/cli

#2379 netcup: increase default propagation values
  providers/dns/netcup/netcup.go
Labels: enhancement, area/dnsprovider

#2381 chore: update dependencies
  go.mod
  go.sum
  providers/dns/huaweicloud/huaweicloud_test.go
Labels: enhancement, area/infrastructure

#2365 Add DNS provider for ManageEngine CloudDNS
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_manageengine.md
  docs/data/zz_cli_help.toml
  providers/dns/manageengine/internal/client.go
  providers/dns/manageengine/internal/client_test.go
  providers/dns/manageengine/internal/fixtures/error.json
  providers/dns/manageengine/internal/fixtures/error_bad_request.json
  providers/dns/manageengine/internal/fixtures/zone_domains_all.json
  providers/dns/manageengine/internal/fixtures/zone_record_create.json
  providers/dns/manageengine/internal/fixtures/zone_record_delete.json
  providers/dns/manageengine/internal/fixtures/zone_record_update.json
  providers/dns/manageengine/internal/fixtures/zone_records_all.json
  providers/dns/manageengine/internal/identity.go
  providers/dns/manageengine/internal/types.go
  providers/dns/manageengine/manageengine.go
  providers/dns/manageengine/manageengine.toml
  providers/dns/manageengine/manageengine_test.go
  providers/dns/zz_gen_dns_providers.go
Labels: enhancement, area/dnsprovider

#2383 chore: update dependencies
  go.mod
  go.sum
Labels: enhancement, area/infrastructure
