Repository go-acme/lego, pull requests merged in 2024-04, with the labels that each got.

#2152 Add DNS provider for Selectel v2
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_selectelv2.md
  docs/data/zz_cli_help.toml
  go.mod
  go.sum
  providers/dns/dns_providers.go
  providers/dns/selectelv2/selectelv2.go
  providers/dns/selectelv2/selectelv2.toml
  providers/dns/selectelv2/selectelv2_test.go
Labels: enhancement, area/dnsprovider

#2155 oracle: update API client
  go.mod
  go.sum
  providers/dns/oraclecloud/configprovider.go
  providers/dns/oraclecloud/oraclecloud.go
  providers/dns/oraclecloud/oraclecloud_test.go
Labels: enhancement, area/dnsprovider

#2156 chore: update dependencies
  go.mod
  go.sum
Labels: enhancement, area/infrastructure

#2160 feat: fills LEGO_CERT_PFX_PATH and LEGO_CERT_PEM_PATH only when needed
  .golangci.yml
  cmd/cmd_renew.go
  docs/content/usage/cli/Obtain-a-Certificate.md
  docs/content/usage/cli/Renew-a-Certificate.md
Labels: enhancement, area/cli

#2166 exec: stream command output
  providers/dns/exec/exec.go
Labels: enhancement, area/dnsprovider
