Repository go-acme/lego, pull requests merged in 2024-08, with the labels that each got.

#2239 cloudflare: update documentation to specify the unit of time-based options
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_cloudflare.md
  providers/dns/cloudflare/cloudflare.toml
Labels: enhancement, area/dnsprovider, area/documentation

#2241 chore: update go version inside go.mod
  go.mod
Labels: area/infrastructure

#2246 fix: avoid Int63n panic in ShouldRenewAt()
  certificate/renewal.go
Labels: bug, area/ari

#2248 Add DNS provider for Lima-City
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_limacity.md
  docs/data/zz_cli_help.toml
  providers/dns/dns_providers.go
  providers/dns/limacity/internal/client.go
  providers/dns/limacity/internal/client_test.go
  providers/dns/limacity/internal/fixtures/error.json
  providers/dns/limacity/internal/fixtures/get-domains.json
  providers/dns/limacity/internal/fixtures/get-records.json
  providers/dns/limacity/internal/fixtures/ok.json
  providers/dns/limacity/internal/types.go
  providers/dns/limacity/limacity.go
  providers/dns/limacity/limacity.toml
  providers/dns/limacity/limacity_test.go
Labels: enhancement, area/dnsprovider

#2200 Add DNS provider for Mittwald
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_mittwald.md
  docs/data/zz_cli_help.toml
  providers/dns/dns_providers.go
  providers/dns/mittwald/internal/client.go
  providers/dns/mittwald/internal/client_test.go
  providers/dns/mittwald/internal/fixtures/dns-create-dns-zone.json
  providers/dns/mittwald/internal/fixtures/dns-get-dns-zone.json
  providers/dns/mittwald/internal/fixtures/dns-list-dns-zones.json
  providers/dns/mittwald/internal/fixtures/domain-list-domains.json
  providers/dns/mittwald/internal/fixtures/error-client.json
  providers/dns/mittwald/internal/fixtures/error.json
  providers/dns/mittwald/internal/types.go
  providers/dns/mittwald/mittwald.go
  providers/dns/mittwald/mittwald.toml
  providers/dns/mittwald/mittwald_test.go
Labels: enhancement, area/dnsprovider
