Repository go-acme/lego, pull requests merged in 2024-11, with the labels that each got.

#2317 fix: Parse printf verbs in log line output
  cmd/setup_challenges.go
Labels: bug, area/log

#2320 Add DNS provider for Regfish
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_regfish.md
  docs/data/zz_cli_help.toml
  go.mod
  go.sum
  providers/dns/regfish/regfish.go
  providers/dns/regfish/regfish.toml
  providers/dns/regfish/regfish_test.go
  providers/dns/zz_gen_dns_providers.go
Labels: enhancement, area/dnsprovider

#2116 brandit: provider deprecation
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_brandit.md
  providers/dns/brandit/brandit.toml
Labels: enhancement, area/dnsprovider

#2324 cloudxns: provider deprecation
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_cloudxns.md
  providers/dns/cloudxns/cloudxns.go
  providers/dns/cloudxns/cloudxns.toml
  providers/dns/cloudxns/cloudxns_test.go
  providers/dns/cloudxns/internal/client.go
  providers/dns/cloudxns/internal/client_test.go
  providers/dns/cloudxns/internal/types.go
Labels: enhancement, area/dnsprovider

#2330 rfc2136: add support for tsig-keygen generated file
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_rfc2136.md
  providers/dns/rfc2136/internal/fixtures/invalid_field.conf
  providers/dns/rfc2136/internal/fixtures/invalid_key.conf
  providers/dns/rfc2136/internal/fixtures/mising_algo.conf
  providers/dns/rfc2136/internal/fixtures/missing_secret.conf
  providers/dns/rfc2136/internal/fixtures/sample.conf
  providers/dns/rfc2136/internal/fixtures/text_after.conf
  providers/dns/rfc2136/internal/fixtures/text_before.conf
  providers/dns/rfc2136/internal/readme.md
  providers/dns/rfc2136/internal/tsigkey.go
  providers/dns/rfc2136/internal/tsigkey_test.go
  providers/dns/rfc2136/rfc2136.go
  providers/dns/rfc2136/rfc2136.toml
  providers/dns/rfc2136/rfc2136_test.go
Labels: enhancement, area/dnsprovider

#2332 Add DNS provider for Technitium
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_technitium.md
  docs/data/zz_cli_help.toml
  providers/dns/technitium/internal/client.go
  providers/dns/technitium/internal/client_test.go
  providers/dns/technitium/internal/fixtures/add-record.json
  providers/dns/technitium/internal/fixtures/delete-record.json
  providers/dns/technitium/internal/fixtures/error.json
  providers/dns/technitium/internal/types.go
  providers/dns/technitium/technitium.go
  providers/dns/technitium/technitium.toml
  providers/dns/technitium/technitium_test.go
  providers/dns/zz_gen_dns_providers.go
Labels: enhancement, area/dnsprovider

#2335 feat: skip the TLS verification of the ACME server
  cmd/flags.go
  cmd/setup.go
  docs/data/zz_cli_help.toml
Labels: enhancement, area/cli

#2337 docs: add documentation for env var only options
  docs/content/usage/cli/Options.md
Labels: enhancement, area/documentation

#2339 docs: update least privilege instructions for Cloudflare
  docs/content/dns/zz_gen_cloudflare.md
  providers/dns/cloudflare/cloudflare.toml
Labels: enhancement, area/dnsprovider, area/documentation

#2298 feat: attempt to check ARI unless explicitly disabled
  cmd/cmd_renew.go
  docs/data/zz_cli_help.toml
Labels: enhancement, breaking-change, area/ari

#2340 chore: domain merge simplification
  cmd/cmd_renew.go
Labels: area/cli, area/infrastructure

#2341 chore: update linter
  .github/workflows/pr.yml
  .golangci.yml
  providers/dns/auroradns/auroradns_test.go
Labels: enhancement, area/infrastructure

#2345 fix: HTTP server IPv6 matching
  challenge/http01/domain_matcher.go
  challenge/http01/domain_matcher_test.go
  challenge/http01/http_challenge_server.go
Labels: bug, area/httpprovider

#2346 docs: improve changelog style
  CHANGELOG.md
Labels: enhancement, area/documentation

#2348 chore: restore snap packaging
  .goreleaser.yml
Labels: bug, area/infrastructure

#2349 chore: fix snap name
  .goreleaser.yml
Labels: bug, area/infrastructure

#2351 directadmin: fix timeout configuration
  providers/dns/directadmin/directadmin.go
Labels: bug, area/dnsprovider

#2356 chore: publish aur lego-bin
  .github/workflows/release.yml
  .goreleaser.yml
Labels: enhancement, area/infrastructure

#2357 technitium: fix status code handling
  providers/dns/technitium/internal/client.go
Labels: bug, area/dnsprovider

#2355 feat: add --force-cert-domains flag to renew
  cmd/cmd_renew.go
Labels: enhancement, area/cli

#2364 docs: add note about --dns.resolvers
  docs/content/usage/cli/Obtain-a-Certificate.md
  docs/data/zz_cli_help.toml
Labels: enhancement, area/documentation
