Repository go-acme/lego, pull requests merged in 2024-02, with the labels that each got.

#2100 route53: fix example
  docs/content/dns/zz_gen_route53.md
  providers/dns/route53/route53.toml
Labels: bug, area/dnsprovider, area/documentation

#1977 Add DNS provider for CPanel and WHM
  .golangci.yml
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_cpanel.md
  docs/data/zz_cli_help.toml
  providers/dns/cpanel/cpanel.go
  providers/dns/cpanel/cpanel.toml
  providers/dns/cpanel/cpanel_test.go
  providers/dns/cpanel/internal/cpanel/client.go
  providers/dns/cpanel/internal/cpanel/client_test.go
  providers/dns/cpanel/internal/cpanel/fixtures/update-zone.json
  providers/dns/cpanel/internal/cpanel/fixtures/update-zone_error.json
  providers/dns/cpanel/internal/cpanel/fixtures/zone-info.json
  providers/dns/cpanel/internal/cpanel/fixtures/zone-info_error.json
  providers/dns/cpanel/internal/cpanel/types.go
  providers/dns/cpanel/internal/shared/dns.go
  providers/dns/cpanel/internal/shared/types.go
  providers/dns/cpanel/internal/whm/client.go
  providers/dns/cpanel/internal/whm/client_test.go
  providers/dns/cpanel/internal/whm/fixtures/update-zone.json
  providers/dns/cpanel/internal/whm/fixtures/update-zone_error.json
  providers/dns/cpanel/internal/whm/fixtures/zone-info.json
  providers/dns/cpanel/internal/whm/fixtures/zone-info_error.json
  providers/dns/cpanel/internal/whm/types.go
  providers/dns/dns_providers.go
Labels: enhancement, area/dnsprovider

#2102 cpanel: remove custom DNS call
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_cpanel.md
  providers/dns/cpanel/cpanel.go
  providers/dns/cpanel/cpanel.toml
  providers/dns/cpanel/cpanel_test.go
  providers/dns/cpanel/internal/shared/dns.go
Labels: enhancement, area/dnsprovider

#2103 chore: update to go1.21
  .github/workflows/pr.yml
  .golangci.yml
  acme/api/account.go
  certcrypto/crypto.go
  cmd/cmd_renew.go
  cmd/cmd_run.go
  go.mod
  go.sum
  platform/config/env/env_test.go
  providers/dns/alidns/alidns.go
  providers/dns/azuredns/oidc.go
  providers/dns/checkdomain/checkdomain.go
  providers/dns/cloudru/internal/client.go
  providers/dns/cpanel/cpanel.go
  providers/dns/designate/designate.go
  providers/dns/edgedns/edgedns.go
  providers/dns/googledomains/googledomains.go
  providers/dns/iij/iij.go
  providers/dns/loopia/loopia_mock_test.go
  providers/dns/mythicbeasts/internal/client.go
  providers/dns/nicmanager/nicmanager.go
  providers/dns/servercow/servercow.go
  providers/dns/transip/fakeclient_test.go
  providers/dns/vkcloud/vkcloud.go
  providers/dns/yandex/yandex.go
  providers/dns/yandexcloud/yandexcloud.go
  providers/http/memcached/memcached_test.go
  providers/http/s3/s3.go
Labels: enhancement, area/infrastructure

#2106 chore: fix typo
  CHANGELOG.md
Labels: area/documentation

#2108 chore: minor changes
  .golangci.yml
  certcrypto/crypto_test.go
  certificate/authorization.go
  challenge/dns01/nameserver.go
  docs/Makefile
  platform/tester/env.go
  providers/dns/cloudxns/internal/client.go
  providers/dns/constellix/constellix.go
  providers/dns/edgedns/edgedns.go
  providers/dns/oraclecloud/configprovider.go
  providers/dns/yandexcloud/yandexcloud.go
Labels: enhancement

#2115 ns1: fix record creation
  .github/workflows/pr.yml
  providers/dns/ns1/ns1.go
Labels: bug, area/dnsprovider

#2119 fix: test on CI
  .github/workflows/documentation.yml
  .github/workflows/pr.yml
  challenge/dns01/fqdn_test.go
  providers/dns/cloudns/internal/client_test.go
  providers/dns/cloudxns/internal/client_test.go
  providers/dns/edgedns/edgedns_test.go
  providers/dns/exoscale/exoscale_test.go
  providers/dns/linode/linode_test.go
Labels: bug, area/infrastructure
