Repository go-acme/lego, pull requests merged in 2024-09, with the labels that each got.

#2260 docs: update installation for FreeBSD
  docs/content/installation/_index.md
Labels: enhancement, area/cli, area/documentation

#2261 docs: add installation for OpenBSD
  docs/content/installation/_index.md
Labels: enhancement, area/cli, area/documentation

#2264 docs: fix typos in some DNS descriptors
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_dnshomede.md
  docs/content/dns/zz_gen_hurricane.md
  providers/dns/dnshomede/dnshomede.toml
  providers/dns/hurricane/hurricane.toml
Labels: area/dnsprovider, area/documentation

#2266 feat(cli): add dns.propagation-wait flag
  cmd/flags.go
  cmd/setup_challenges.go
  docs/data/zz_cli_help.toml
Labels: enhancement, area/dnsprovider, area/cli

#2256 exoscale: update Egoscale to v3.1.1
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_exoscale.md
  go.mod
  go.sum
  providers/dns/exoscale/exoscale.go
  providers/dns/exoscale/exoscale.toml
Labels: area/dnsprovider, area/infrastructure

#2267 Add DNS provider for HuaweiCloud
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_huaweicloud.md
  docs/data/zz_cli_help.toml
  go.mod
  go.sum
  providers/dns/dns_providers.go
  providers/dns/huaweicloud/huaweicloud.go
  providers/dns/huaweicloud/huaweicloud.toml
  providers/dns/huaweicloud/huaweicloud_test.go
Labels: enhancement, area/dnsprovider

#2270 godaddy: fix cleanup
  providers/dns/godaddy/godaddy.go
  providers/dns/godaddy/internal/client.go
  providers/dns/godaddy/internal/client_test.go
  providers/dns/godaddy/internal/fixtures/error-extended.json
  providers/dns/godaddy/internal/types.go
Labels: bug, area/dnsprovider

#2275 chore: use UTC instead of GMT when possible
  providers/dns/brandit/internal/client.go
  providers/dns/nifcloud/internal/client.go
  providers/dns/websupport/internal/client.go
Labels: area/dnsprovider

#2281 ionos: follow CNAME
  providers/dns/ionos/ionos.go
Labels: enhancement, area/dnsprovider

#2278 Add DNS provider for SelfHost.(de|eu)
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_selfhostde.md
  docs/data/zz_cli_help.toml
  providers/dns/dns_providers.go
  providers/dns/selfhostde/internal/client.go
  providers/dns/selfhostde/internal/client_test.go
  providers/dns/selfhostde/internal/readme.md
  providers/dns/selfhostde/mapping.go
  providers/dns/selfhostde/mapping_test.go
  providers/dns/selfhostde/selfhostde.go
  providers/dns/selfhostde/selfhostde.toml
  providers/dns/selfhostde/selfhostde_test.go
Labels: enhancement, area/dnsprovider

#2283 chore: use contants for flag names
  cmd/accounts_storage.go
  cmd/certs_storage.go
  cmd/cmd_before.go
  cmd/cmd_dnshelp.go
  cmd/cmd_list.go
  cmd/cmd_renew.go
  cmd/cmd_revoke.go
  cmd/cmd_run.go
  cmd/flags.go
  cmd/setup.go
  cmd/setup_challenges.go
Labels: enhancement, area/infrastructure

#2284 feat: add dns.propagation-rns option
  challenge/dns01/precheck.go
  challenge/dns01/precheck_test.go
  cmd/flags.go
  cmd/setup_challenges.go
  docs/data/zz_cli_help.toml
  e2e/dnschallenge/dns_challenges_test.go
Labels: enhancement, area/lib, area/cli

#2287 namesilo: restrict CleanUp
  providers/dns/namesilo/namesilo.go
Labels: bug, area/dnsprovider
