Repository go-acme/lego, pull requests merged in 2024-01, with the labels that each got.

#2075 scaleway: add cname support
  go.mod
  go.sum
  providers/dns/scaleway/scaleway.go
Labels: enhancement, area/dnsprovider

#2076 cloudru: change default URLs
  providers/dns/cloudru/internal/client.go
Labels: enhancement, area/dnsprovider

#2077 Add DNS provider for Webnames
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_webnames.md
  docs/data/zz_cli_help.toml
  providers/dns/dns_providers.go
  providers/dns/webnames/internal/client.go
  providers/dns/webnames/internal/client_test.go
  providers/dns/webnames/internal/fixtures/error.json
  providers/dns/webnames/internal/fixtures/ok.json
  providers/dns/webnames/internal/types.go
  providers/dns/webnames/webnames.go
  providers/dns/webnames/webnames.toml
  providers/dns/webnames/webnames_test.go
Labels: enhancement, area/dnsprovider

#2061 feat(cli): add environment variable for specifying alternate directory URL
  cmd/flags.go
  docs/data/zz_cli_help.toml
Labels: enhancement, area/cli

#2083 ionos: fix DNS record removal
  providers/dns/ionos/ionos.go
Labels: bug, area/dnsprovider

#2084 inwx: wait before generating new TOTP TANs
  providers/dns/inwx/inwx.go
  providers/dns/inwx/inwx_test.go
Labels: bug, area/dnsprovider

#2081 gcloud: support GCE_ZONE_ID to bypass zone list
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_gcloud.md
  providers/dns/gcloud/gcloud.toml
  providers/dns/gcloud/googlecloud.go
Labels: enhancement, area/dnsprovider

#2086 inwx: improve sleep calculation
  providers/dns/inwx/inwx.go
  providers/dns/inwx/inwx_test.go
Labels: enhancement, area/dnsprovider

#2085 constellix: follow rate limiting headers
  providers/dns/constellix/constellix.go
Labels: bug, area/dnsprovider

#2066 Update CertID format as per draft-ietf-acme-ari-02
  .golangci.yml
  README.md
  acme/commons.go
  certificate/renewal.go
  certificate/renewal_test.go
  cmd/cmd_renew.go
  docs/data/zz_cli_help.toml
Labels: enhancement, area/lib, breaking-change

#2089 desec: increase default propagation interval
  providers/dns/desec/desec.go
Labels: enhancement, area/dnsprovider

#2054 feat: support simplified issuance for very long domain names at Let's Encrypt
  certcrypto/crypto.go
  certificate/certificates.go
  cmd/cmd_list.go
  cmd/cmd_renew.go
Labels: enhancement, area/lib

#2019 pdns: optional custom API version
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_pdns.md
  docs/data/zz_cli_help.toml
  providers/dns/pdns/internal/client.go
  providers/dns/pdns/internal/client_test.go
  providers/dns/pdns/pdns.go
  providers/dns/pdns/pdns.toml
  providers/dns/pdns/pdns_test.go
Labels: enhancement, area/dnsprovider

#2063 cli: add format option for PFX encoding
  cmd/certs_storage.go
  cmd/flags.go
  docs/data/zz_cli_help.toml
  go.mod
  go.sum
Labels: enhancement, area/cli

#2092 chore: update dependencies
  docs/data/zz_cli_help.toml
  go.mod
  go.sum
  providers/dns/ns1/ns1.go
Labels: enhancement, area/infrastructure

#2094 docs: add installation for Gentoo
  docs/content/installation/_index.md
Labels: enhancement, area/documentation

#2095 chore: replace mitchellh/mapstructure by go-viper/mapstructure/v2
  go.mod
  go.sum
  providers/dns/allinkl/internal/client.go
Labels: enhancement, area/infrastructure
