Repository go-acme/lego, pull requests merged in 2024-06, with the labels that each got.

#2205 chore: update dependencies
  go.mod
  go.sum
  providers/dns/lightsail/lightsail_test.go
  providers/dns/route53/route53_test.go
Labels: bug, area/infrastructure

#2206 chore: update linter
  .github/workflows/pr.yml
  .golangci.yml
  docs/data/zz_cli_help.toml
  go.sum
  providers/dns/dynu/internal/client_test.go
  providers/dns/rcodezero/internal/client_test.go
  providers/dns/servercow/internal/client_test.go
Labels: enhancement, area/infrastructure

#2209 feat: add option to handle the overall request limit
  certificate/authorization.go
  certificate/certificates.go
  cmd/flags.go
  cmd/setup.go
  docs/data/zz_cli_help.toml
  lego/client.go
  lego/client_config.go
Labels: enhancement, area/lib, area/cli

#2210 feat: expose certificates pool creation
  challenge/http01/domain_matcher.go
  lego/client_config.go
  providers/dns/acmedns/acmedns_test.go
Labels: enhancement, area/lib

#2201 docs: add note about snap
  docs/content/installation/_index.md
Labels: enhancement, area/documentation

#2216 ovh: allow to use ovh.conf file
  providers/dns/ovh/ovh.go
  providers/dns/ovh/ovh_test.go
Labels: enhancement, area/dnsprovider

#2217 fix: restore Solaris
  .goreleaser.yml
  go.mod
  go.sum
Labels: bug, area/infrastructure
