Repository go-acme/lego, pull requests merged in 2024-03, with the labels that each got.

#2121 easydns: fix zone detection
  providers/dns/easydns/easydns.go
  providers/dns/easydns/easydns_test.go
  providers/dns/easydns/internal/client.go
  providers/dns/easydns/internal/client_test.go
  providers/dns/easydns/internal/fixtures/error.json
  providers/dns/easydns/internal/fixtures/error1.json
  providers/dns/easydns/internal/fixtures/list-zone.json
  providers/dns/easydns/internal/readme.md
  providers/dns/easydns/internal/types.go
Labels: bug, area/dnsprovider

#2130 chore: update to github.com/go-jose/go-jose/v4
  acme/api/internal/secure/jws.go
  acme/api/order_test.go
  certificate/renewal_test.go
  challenge/resolver/solver_manager_test.go
  go.mod
  go.sum
  providers/dns/hyperone/internal/token.go
Labels: bug, area/infrastructure

#2114 Implement 'replaces' field in newOrder and draft-ietf-acme-ari-03 CertID changes
  .golangci.yml
  README.md
  acme/api/order.go
  acme/commons.go
  certificate/certificates.go
  certificate/renewal.go
  certificate/renewal_test.go
  cmd/cmd_renew.go
Labels: enhancement, area/lib, area/ari

#2126 Add DNS provider for Shellrent
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_shellrent.md
  docs/data/zz_cli_help.toml
  providers/dns/dns_providers.go
  providers/dns/shellrent/internal/client.go
  providers/dns/shellrent/internal/client_test.go
  providers/dns/shellrent/internal/fixtures/dns_record-remove.json
  providers/dns/shellrent/internal/fixtures/dns_record-store.json
  providers/dns/shellrent/internal/fixtures/domain-details.json
  providers/dns/shellrent/internal/fixtures/error.json
  providers/dns/shellrent/internal/fixtures/purchase-details.json
  providers/dns/shellrent/internal/fixtures/purchase.json
  providers/dns/shellrent/internal/types.go
  providers/dns/shellrent/shellrent.go
  providers/dns/shellrent/shellrent.toml
  providers/dns/shellrent/shellrent_test.go
Labels: enhancement, area/dnsprovider

#2138 fix: don't generate ARI cert ID if ARI is not enable
  cmd/cmd_renew.go
Labels: bug, area/cli, area/ari

#2134 chore: add snap to release packages
  .github/workflows/release.yml
  .goreleaser.yml
  docs/content/installation/_index.md
Labels: enhancement, area/infrastructure

#2136 scaleway: add alternative env var names
  CHANGELOG.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_scaleway.md
  providers/dns/scaleway/scaleway.go
  providers/dns/scaleway/scaleway.toml
  providers/dns/scaleway/scaleway_test.go
Labels: enhancement, area/dnsprovider

#2140 azuredns: servicediscovery for zones
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_azuredns.md
  go.mod
  go.sum
  providers/dns/azuredns/azuredns.go
  providers/dns/azuredns/azuredns.toml
  providers/dns/azuredns/azuredns_test.go
  providers/dns/azuredns/private.go
  providers/dns/azuredns/public.go
  providers/dns/azuredns/servicediscovery.go
  providers/dns/azuredns/servicediscovery_test.go
Labels: enhancement, area/dnsprovider

#2144 chore: update to go1.22
  .github/workflows/go-cross.yml
  .github/workflows/pr.yml
  .golangci.yml
  acme/api/order_test.go
  acme/api/service_test.go
  certcrypto/crypto_test.go
  certificate/authorization.go
  certificate/renewal_test.go
  challenge/dns01/dns_challenge.go
  challenge/dns01/domain_test.go
  challenge/dns01/fqdn_test.go
  challenge/dns01/nameserver_test.go
  challenge/dns01/precheck_test.go
  challenge/http01/domain_matcher_test.go
  challenge/http01/http_challenge_test.go
  challenge/resolver/prober_test.go
  cmd/cmd_renew_test.go
  docs/content/installation/_index.md
  go.mod
  platform/config/env/env_test.go
  providers/dns/azuredns/private.go
  providers/dns/azuredns/public.go
  providers/dns/azuredns/servicediscovery_test.go
  providers/dns/dreamhost/internal/client_test.go
  providers/dns/duckdns/internal/client_test.go
  providers/dns/dynu/internal/client_test.go
  providers/dns/edgedns/edgedns_test.go
  providers/dns/exoscale/exoscale_test.go
  providers/dns/gcore/gcore_test.go
  providers/dns/httpreq/httpreq_test.go
  providers/dns/hurricane/internal/client_test.go
  providers/dns/iij/iij.go
  providers/dns/iij/iij_test.go
  providers/dns/inwx/inwx_test.go
  providers/dns/ionos/ionos.go
  providers/dns/ipv64/ipv64_test.go
  providers/dns/joker/internal/dmapi/client_test.go
  providers/dns/liquidweb/liquidweb_test.go
  providers/dns/luadns/luadns.go
  providers/dns/luadns/luadns_test.go
  providers/dns/namecheap/namecheap_test.go
  providers/dns/nearlyfreespeech/internal/client.go
  providers/dns/nearlyfreespeech/internal/client_test.go
  providers/dns/netcup/internal/client_test.go
  providers/dns/netcup/internal/session_test.go
  providers/dns/nifcloud/internal/client_test.go
  providers/dns/pdns/internal/client_test.go
  providers/dns/regru/internal/client_test.go
  providers/dns/sakuracloud/wrapper_test.go
  providers/dns/shellrent/internal/client_test.go
  providers/dns/sonic/internal/client_test.go
  providers/dns/stackpath/stackpath_test.go
  providers/dns/vinyldns/vinyldns_test.go
  providers/dns/vultr/vultr_test.go
  providers/dns/webnames/internal/client_test.go
  providers/dns/yandex/internal/client_test.go
  providers/dns/yandex/yandex.go
  providers/dns/zoneee/zoneee_test.go
Labels: enhancement, area/infrastructure

#2145 docs: fix link to alibaba API documentation
  docs/content/dns/zz_gen_alidns.md
  providers/dns/alidns/alidns.toml
Labels: area/dnsprovider, area/documentation

#2146 httpnet: add provider to NewDNSChallengeProviderByName
  providers/dns/dns_providers.go
Labels: bug, area/dnsprovider
