Repository go-acme/lego, pull requests merged in 2025-07, with the labels that each got.

#2552 chore: update linter
  .github/workflows/pr.yml
  .golangci.yml
Labels: enhancement, area/infrastructure

#2555 azion: add pagination support
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_azion.md
  providers/dns/azion/azion.go
  providers/dns/azion/azion.toml
Labels: bug, area/dnsprovider

#2556 oraclecloud: replace oci-go-sdk by a modular fork
  go.mod
  go.sum
  providers/dns/oraclecloud/configprovider.go
  providers/dns/oraclecloud/oraclecloud.go
  providers/dns/oraclecloud/oraclecloud_test.go
Labels: enhancement, area/dnsprovider, area/infrastructure

#2558 alidns: migrate to SDK v2
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_alidns.md
  docs/content/dns/zz_gen_googledomains.md
  go.mod
  go.sum
  providers/dns/alidns/alidns.go
  providers/dns/alidns/alidns.toml
Labels: enhancement, area/dnsprovider, area/infrastructure

#2562 mijnhost: improve record filter
  providers/dns/mijnhost/mijnhost.go
Labels: bug, area/dnsprovider

#2564 azion: improve zone lookup
  providers/dns/azion/azion.go
  providers/dns/azion/azion_test.go
  providers/dns/azion/fixtures/zones.json
  providers/dns/azion/fixtures/zones_empty.json
Labels: bug, area/dnsprovider

#2570 feat: add option to disable common name in CSR
  certificate/certificates.go
  cmd/flags.go
  cmd/setup.go
  lego/client.go
  lego/client_config.go
Labels: enhancement, area/lib, area/cli

#2574 feat: add option to define dynamically the renew date
  cmd/cmd_renew.go
  cmd/cmd_renew_test.go
  docs/data/zz_cli_help.toml
Labels: enhancement, area/cli

#2580 vinyldns: add an option to add quotes around the TXT record value
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_vinyldns.md
  providers/dns/vinyldns/vinyldns.go
  providers/dns/vinyldns/vinyldns.toml
Labels: enhancement, area/dnsprovider

#2578 Add DNS provider for ZoneEdit
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_zoneedit.md
  docs/data/zz_cli_help.toml
  providers/dns/zoneedit/internal/client.go
  providers/dns/zoneedit/internal/client_test.go
  providers/dns/zoneedit/internal/fixtures/error.xml
  providers/dns/zoneedit/internal/fixtures/success.xml
  providers/dns/zoneedit/internal/types.go
  providers/dns/zoneedit/zoneedit.go
  providers/dns/zoneedit/zoneedit.toml
  providers/dns/zoneedit/zoneedit_test.go
  providers/dns/zz_gen_dns_providers.go
Labels: enhancement, area/dnsprovider

#2582 chore: check generated files
  .github/workflows/pr.yml
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_zoneedit.md
Labels: area/infrastructure

#2584 chore: replace official Civo API client by an internal API client
  go.mod
  go.sum
  providers/dns/civo/civo.go
  providers/dns/civo/civo_test.go
  providers/dns/civo/internal/client.go
  providers/dns/civo/internal/client_test.go
  providers/dns/civo/internal/fixtures/create_dns_record-request.json
  providers/dns/civo/internal/fixtures/create_dns_record.json
  providers/dns/civo/internal/fixtures/delete_dns_record.json
  providers/dns/civo/internal/fixtures/error.json
  providers/dns/civo/internal/fixtures/list_dns_records.json
  providers/dns/civo/internal/fixtures/list_domain_names.json
  providers/dns/civo/internal/types.go
Labels: enhancement, area/dnsprovider, area/infrastructure

#2585 chore: migrate to yandex cloud API Client v2
  go.mod
  go.sum
  providers/dns/yandexcloud/yandexcloud.go
Labels: enhancement, area/dnsprovider, area/infrastructure

#2586 tests: improve function naming
  platform/tester/servermock/handler_file.go
  platform/tester/servermock/link_request_body.go
  platform/tester/servermock/link_request_body_json.go
  providers/dns/acmedns/internal/http_storage_test.go
  providers/dns/allinkl/internal/client_test.go
  providers/dns/arvancloud/internal/client_test.go
  providers/dns/autodns/internal/client_test.go
  providers/dns/checkdomain/internal/client_test.go
  providers/dns/civo/civo_test.go
  providers/dns/civo/internal/client_test.go
  providers/dns/clouddns/internal/client_test.go
  providers/dns/clouddns/internal/identity_test.go
  providers/dns/cloudflare/cloudflare_test.go
  providers/dns/cloudflare/internal/client_test.go
  providers/dns/dnsmadeeasy/internal/client_test.go
  providers/dns/domeneshop/internal/client_test.go
  providers/dns/dynu/internal/client_test.go
  providers/dns/gandi/internal/client_test.go
  providers/dns/godaddy/internal/client_test.go
  providers/dns/hetzner/internal/client_test.go
  providers/dns/infomaniak/internal/client_test.go
  providers/dns/internal/hostingde/client_test.go
  providers/dns/internal/selectel/client_test.go
  providers/dns/namecheap/namecheap_test.go
  providers/dns/netcup/internal/client_test.go
  providers/dns/netcup/internal/session_test.go
  providers/dns/njalla/internal/client_test.go
  providers/dns/otc/otc_test.go
  providers/dns/pdns/internal/client_test.go
  providers/dns/safedns/internal/client_test.go
  providers/dns/versio/internal/client_test.go
Labels: enhancement, area/infrastructure

#2587 chore: use custom API client constructor for sakuracloud
  providers/dns/sakuracloud/sakuracloud.go
Labels: enhancement, area/dnsprovider, area/infrastructure

#2588 tencentcloud: replace tencentcloud-sdk-go with a fork
  go.mod
  go.sum
  providers/dns/tencentcloud/tencentcloud.go
  providers/dns/tencentcloud/wrapper.go
Labels: enhancement, area/dnsprovider, area/infrastructure

#2589 alidns: replace alidns-20150109 with a fork
  go.mod
  go.sum
  providers/dns/alidns/alidns.go
Labels: enhancement, area/dnsprovider, area/infrastructure

#2591 huaweicloud: lightweight client
  .golangci.yml
  providers/dns/huaweicloud/huaweicloud.go
  providers/dns/huaweicloud/internal/client.go
Labels: enhancement, area/dnsprovider, area/infrastructure

#2592 chore: update dependencies
  go.mod
  go.sum
  providers/dns/ovh/ovh_test.go
Labels: enhancement, area/infrastructure

#2595 fix: wrong CLI flag type
  cmd/flags.go
  docs/data/zz_cli_help.toml
Labels: bug, area/cli

#2600 fix: remove wrong env var
  cmd/flags.go
  docs/data/zz_cli_help.toml
Labels: bug, area/cli

#2602 chore: clean up tests and code
  acme/api/certificate.go
  acme/api/certificate_test.go
  acme/api/order_test.go
  certificate/certificates_test.go
  certificate/renewal_test.go
  challenge/dns01/dns_challenge_test.go
  challenge/http01/http_challenge_test.go
  challenge/resolver/prober_test.go
  challenge/resolver/solver_manager_test.go
  challenge/tlsalpn01/tls_alpn_challenge_test.go
  lego/client_test.go
  platform/tester/api.go
  providers/dns/constellix/internal/domains_test.go
  providers/dns/constellix/internal/fixtures/domains-GetAll.json
  providers/dns/constellix/internal/fixtures/domains-Search.json
  providers/dns/gcloud/googlecloud_test.go
  providers/dns/servercow/internal/client_test.go
  registration/registar_test.go
Labels: enhancement, area/lib, area/infrastructure

#2603 tests: use better test domains
  .github/workflows/pr.yml
  certcrypto/crypto_test.go
  challenge/dns01/nameserver_test.go
  e2e/challenges_test.go
  e2e/dnschallenge/dns_challenges_test.go
  e2e/fixtures/csr.cert
  e2e/fixtures/csr.raw
  e2e/readme.md
Labels: enhancement, area/infrastructure
