Repository go-acme/lego, pull requests merged in 2025-03, with the labels that each got.

#2460 edgedns: add account switch key option
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_edgedns.md
  providers/dns/edgedns/edgedns.go
  providers/dns/edgedns/edgedns.toml
  providers/dns/edgedns/edgedns_test.go
Labels: enhancement, area/dnsprovider

#2409 Add DNS provider for F5 XC
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_f5xc.md
  docs/data/zz_cli_help.toml
  providers/dns/f5xc/f5xc.go
  providers/dns/f5xc/f5xc.toml
  providers/dns/f5xc/f5xc_test.go
  providers/dns/f5xc/internal/client.go
  providers/dns/f5xc/internal/client_test.go
  providers/dns/f5xc/internal/fixtures/create.json
  providers/dns/f5xc/internal/fixtures/delete.json
  providers/dns/f5xc/internal/fixtures/error_404.json
  providers/dns/f5xc/internal/fixtures/error_503.json
  providers/dns/f5xc/internal/fixtures/get.json
  providers/dns/f5xc/internal/fixtures/replace.json
  providers/dns/f5xc/internal/types.go
  providers/dns/zz_gen_dns_providers.go
Labels: enhancement, area/dnsprovider

#2467 dnssimple: use GetZone
  providers/dns/dnsimple/dnsimple.go
Labels: bug, area/dnsprovider

#2469 fix: kill hook when the command is stuck
  cmd/hook.go
  cmd/hook_test.go
  cmd/testdata/sleeping_beauty.sh
  cmd/testdata/sleepy.sh
Labels: bug, area/cli

#2470 chore: update dependencies
  go.mod
  go.sum
Labels: enhancement, area/infrastructure

#2471 chore: related timer with context.Done
  cmd/hook.go
  cmd/hook_test.go
Labels: area/cli

#2478 Add DNS provider for Active24
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_active24.md
  docs/data/zz_cli_help.toml
  providers/dns/active24/active24.go
  providers/dns/active24/active24.toml
  providers/dns/active24/active24_test.go
  providers/dns/active24/internal/client.go
  providers/dns/active24/internal/client_test.go
  providers/dns/active24/internal/fixtures/error_403.json
  providers/dns/active24/internal/fixtures/error_422.json
  providers/dns/active24/internal/fixtures/error_v1.json
  providers/dns/active24/internal/fixtures/records.json
  providers/dns/active24/internal/fixtures/services.json
  providers/dns/active24/internal/types.go
  providers/dns/zz_gen_dns_providers.go
Labels: enhancement, area/dnsprovider

#2479 websupport: migrate to API v2
  docs/content/dns/zz_gen_websupport.md
  providers/dns/active24/active24.go
  providers/dns/active24/active24.toml
  providers/dns/internal/active24/client.go
  providers/dns/internal/active24/client_test.go
  providers/dns/internal/active24/fixtures/error_403.json
  providers/dns/internal/active24/fixtures/error_422.json
  providers/dns/internal/active24/fixtures/error_v1.json
  providers/dns/internal/active24/fixtures/records.json
  providers/dns/internal/active24/fixtures/services.json
  providers/dns/internal/active24/types.go
  providers/dns/websupport/internal/client.go
  providers/dns/websupport/internal/client_test.go
  providers/dns/websupport/internal/fixtures/add-record-error-400.json
  providers/dns/websupport/internal/fixtures/add-record-error-404.json
  providers/dns/websupport/internal/fixtures/add-record.json
  providers/dns/websupport/internal/fixtures/delete-record-error-404.json
  providers/dns/websupport/internal/fixtures/delete-record.json
  providers/dns/websupport/internal/fixtures/get-record.json
  providers/dns/websupport/internal/fixtures/get-user.json
  providers/dns/websupport/internal/fixtures/list-records.json
  providers/dns/websupport/internal/types.go
  providers/dns/websupport/websupport.go
  providers/dns/websupport/websupport.toml
  providers/dns/websupport/websupport_test.go
Labels: enhancement, area/dnsprovider

#2475 fix: retry on alreadyReplaced error
  acme/api/internal/sender/sender.go
  acme/api/order.go
  acme/api/order_test.go
  acme/errors.go
Labels: bug, area/ari

#2485 chore: fix feature request template
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: area/infrastructure

#2484 cloudflare: make base URL configurable
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_cloudflare.md
  providers/dns/cloudflare/cloudflare.go
  providers/dns/cloudflare/cloudflare.toml
  providers/dns/cloudflare/cloudflare_test.go
  providers/dns/cloudflare/wrapper.go
Labels: enhancement, area/dnsprovider

#2162 route53: adds option to use private zone
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_route53.md
  providers/dns/route53/route53.go
  providers/dns/route53/route53.toml
  providers/dns/route53/route53_test.go
Labels: enhancement, area/dnsprovider

#2490 allinkl: remove ReturnInfo
  providers/dns/allinkl/internal/client.go
  providers/dns/allinkl/internal/client_test.go
  providers/dns/allinkl/internal/types_api.go
Labels: bug, area/dnsprovider

#2491 chore: update dependencies
  go.mod
  go.sum
Labels: enhancement, area/infrastructure

#2492 chore: update linter
  .github/workflows/pr.yml
  .golangci.yml
  certificate/certificates_test.go
  challenge/dns01/nameserver_test.go
  challenge/http01/domain_matcher_test.go
  challenge/tlsalpn01/tls_alpn_challenge_test.go
  platform/tester/env_test.go
  providers/dns/cloudns/internal/client_test.go
  providers/dns/loopia/internal/client_test.go
  providers/dns/netcup/internal/session_test.go
  providers/dns/oraclecloud/oraclecloud.go
  providers/dns/sakuracloud/wrapper.go
  providers/dns/wedos/internal/token.go
Labels: enhancement, area/infrastructure

#2498 designate: speed up API requests by using filters
  providers/dns/designate/designate.go
Labels: enhancement, area/dnsprovider

#2499 feat: add delay option for TLSALPN challenge
  challenge/resolver/solver_manager.go
  challenge/tlsalpn01/tls_alpn_challenge.go
  cmd/flags.go
  cmd/setup_challenges.go
  docs/data/zz_cli_help.toml
Labels: enhancement, area/lib, area/cli

#2500 pdns: fix TXT record cleanup for wildcard domains
  providers/dns/pdns/pdns.go
  providers/dns/pdns/pdns_test.go
Labels: bug, area/dnsprovider
