Repository go-acme/lego, pull requests merged in 2025-01, with the labels that each got.

#2387 chore: update linter
  .github/workflows/pr.yml
  .golangci.yml
  challenge/dns01/dns_challenge_manual_test.go
  platform/config/env/env_test.go
  providers/dns/designate/designate_test.go
Labels: enhancement, area/infrastructure

#2389 feat: add hook-timeout to run and renew commands
  cmd/cmd_renew.go
  cmd/cmd_run.go
  cmd/hook.go
  docs/data/zz_cli_help.toml
Labels: enhancement, area/cli

#2393 acme-dns: HTTP storage
  .golangci.yml
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_acme-dns.md
  go.mod
  go.sum
  providers/dns/acmedns/acmedns.go
  providers/dns/acmedns/acmedns.toml
  providers/dns/acmedns/acmedns_test.go
  providers/dns/acmedns/internal/fixtures/error.json
  providers/dns/acmedns/internal/fixtures/fetch-all.json
  providers/dns/acmedns/internal/fixtures/fetch.json
  providers/dns/acmedns/internal/http_storage.go
  providers/dns/acmedns/internal/http_storage_test.go
  providers/dns/acmedns/internal/readme.md
  providers/dns/acmedns/mock_test.go
Labels: enhancement, area/dnsprovider

#2398 cli: add environment variable for specifying email
  cmd/flags.go
Labels: enhancement, area/cli

#2399 chore: use constants for env vars related to flags
  cmd/cmd_renew.go
  cmd/cmd_run.go
  cmd/flags.go
  cmd/hook.go
Labels: enhancement, area/cli

#2411 Add DNS provider for myaddr.{tools,dev,io}
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_myaddr.md
  docs/data/zz_cli_help.toml
  providers/dns/myaddr/internal/client.go
  providers/dns/myaddr/internal/client_test.go
  providers/dns/myaddr/internal/fixtures/error.txt
  providers/dns/myaddr/internal/types.go
  providers/dns/myaddr/myaddr.go
  providers/dns/myaddr/myaddr.toml
  providers/dns/myaddr/myaddr_test.go
  providers/dns/zz_gen_dns_providers.go
Labels: enhancement, area/dnsprovider

#2412 fix(cli): remove extra debug logs
  cmd/setup.go
Labels: bug, area/cli, area/log

#2415 feat: add support for Profiles Extension
  .github/workflows/pr.yml
  README.md
  acme/api/order.go
  acme/commons.go
  certificate/certificates.go
  cmd/cmd_renew.go
  cmd/cmd_run.go
  docs/content/_index.md
  e2e/challenges_test.go
  e2e/dnschallenge/dns_challenges_test.go
  e2e/fixtures/pebble-config-dns.json
  e2e/fixtures/pebble-config.json
Labels: enhancement, area/lib, area/cli, area/profiles
