Repository go-acme/lego, pull requests merged in 2025-05, with the labels that each got.

#2521 cloudflare: add quotation marks to TXT record
  providers/dns/cloudflare/cloudflare.go
Labels: enhancement, area/dnsprovider

#1892 Add DNS provider for RU Center
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_nicru.md
  docs/data/zz_cli_help.toml
  providers/dns/nicru/internal/client.go
  providers/dns/nicru/internal/client_test.go
  providers/dns/nicru/internal/fixtures/commit_POST.xml
  providers/dns/nicru/internal/fixtures/errors.xml
  providers/dns/nicru/internal/fixtures/record_DELETE.xml
  providers/dns/nicru/internal/fixtures/records_GET.xml
  providers/dns/nicru/internal/fixtures/records_PUT.xml
  providers/dns/nicru/internal/fixtures/services_GET.xml
  providers/dns/nicru/internal/fixtures/zones_GET.xml
  providers/dns/nicru/internal/fixtures/zones_all_GET.xml
  providers/dns/nicru/internal/identity.go
  providers/dns/nicru/internal/types.go
  providers/dns/nicru/nicru.go
  providers/dns/nicru/nicru.toml
  providers/dns/nicru/nicru_test.go
  providers/dns/zz_gen_dns_providers.go
Labels: enhancement, area/dnsprovider

#2523 chore: bump dnsimple, namedotcom, and selectel to major versions
  go.mod
  go.sum
  providers/dns/dnsimple/dnsimple.go
  providers/dns/namedotcom/namedotcom.go
  providers/dns/selectelv2/selectelv2.go
Labels: enhancement, area/dnsprovider, area/infrastructure

#2526 pdns: improve error messages
  providers/dns/pdns/pdns.go
Labels: enhancement, area/dnsprovider

#2529 docs(cPanel): fix examples
  docs/content/dns/zz_gen_cpanel.md
  providers/dns/cpanel/cpanel.toml
Labels: area/dnsprovider, area/documentation
