Repository go-acme/lego, pull requests merged in 2025-08, with the labels that each got.

#2608 fix: enforce HTTPS to the ACME server
  acme/api/certificate_test.go
  acme/api/internal/nonces/nonce_manager_test.go
  acme/api/internal/secure/jws_test.go
  acme/api/internal/sender/sender.go
  acme/api/internal/sender/sender_test.go
  acme/api/order_test.go
  certificate/certificates_test.go
  certificate/renewal_test.go
  challenge/dns01/dns_challenge_test.go
  challenge/http01/http_challenge_test.go
  challenge/resolver/solver_manager_test.go
  challenge/tlsalpn01/tls_alpn_challenge_test.go
  lego/client_test.go
  platform/tester/api.go
  platform/tester/servermock/builder.go
  registration/registar_test.go
Labels: bug, area/lib, area/cli

#2610 chore: clean up
  challenge/dns01/fqdn.go
  challenge/dns01/fqdn_test.go
  providers/dns/auroradns/auroradns.go
  providers/dns/gandi/gandi_test.go
  providers/dns/gcloud/googlecloud.go
  providers/dns/otc/internal/client_test.go
  providers/dns/otc/internal/fixtures/zones-recordsets_POST-request.json
  providers/dns/otc/otc_test.go
  providers/dns/safedns/safedns.go
  providers/dns/selectelv2/selectelv2.go
  providers/dns/yandex360/yandex360.go
Labels: enhancement, area/infrastructure

#2611 tests: change the signature of the method BuildHTTPS
  acme/api/certificate_test.go
  acme/api/internal/nonces/nonce_manager_test.go
  acme/api/internal/secure/jws_test.go
  acme/api/order_test.go
  certificate/certificates_test.go
  certificate/renewal_test.go
  challenge/dns01/dns_challenge_test.go
  challenge/http01/http_challenge_test.go
  challenge/resolver/solver_manager_test.go
  challenge/tlsalpn01/tls_alpn_challenge_test.go
  lego/client_test.go
  platform/tester/api.go
  platform/tester/servermock/builder.go
  registration/registar_test.go
Labels: enhancement, area/infrastructure

#2599 oraclecloud: handle instance_principal authentication
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_oraclecloud.md
  providers/dns/oraclecloud/configurationprovider.go
  providers/dns/oraclecloud/fixtures/cert.pem
  providers/dns/oraclecloud/fixtures/key.pem
  providers/dns/oraclecloud/oraclecloud.go
  providers/dns/oraclecloud/oraclecloud.toml
  providers/dns/oraclecloud/oraclecloud_test.go
Labels: enhancement, area/dnsprovider

#2621 azuredns: pipeline credential support
  docs/content/dns/zz_gen_azuredns.md
  providers/dns/azuredns/azuredns.go
  providers/dns/azuredns/azuredns.toml
  providers/dns/azuredns/credentials.go
Labels: enhancement, area/dnsprovider

#2631 simply: update to API v2
  providers/dns/simply/internal/client.go
  providers/dns/simply/internal/client_test.go
  providers/dns/simply/simply.toml
Labels: bug, area/dnsprovider
