Repository go-acme/lego, pull requests merged in 2025-02, with the labels that each got.

#2420 feat(cli): add LEGO_DEBUG_ACME_HTTP_CLIENT to debug the calls to the ACME server
  certificate/authorization.go
  cmd/cmd_run.go
  cmd/setup.go
  docs/content/usage/cli/Options.md
  e2e/challenges_test.go
  e2e/dnschallenge/dns_challenges_test.go
Labels: enhancement, area/cli

#2422 feat: add delay option for HTTP challenge
  challenge/http01/http_challenge.go
  challenge/resolver/solver_manager.go
  cmd/flags.go
  cmd/setup_challenges.go
  docs/data/zz_cli_help.toml
Labels: enhancement, area/lib, area/cli, area/httpprovider

#2423 feat: option to set CSR emails
  certcrypto/crypto.go
  certcrypto/crypto_test.go
  certificate/certificates.go
  e2e/challenges_test.go
Labels: enhancement, area/lib

#2424 chore: update links of liara provider API doc
  docs/content/dns/zz_gen_liara.md
  providers/dns/liara/internal/client.go
  providers/dns/liara/liara.toml
Labels: bug, area/dnsprovider, area/documentation

#2428 fix: rewrite status management
  acme/api/order.go
  acme/commons.go
  acme/errors.go
  certificate/certificates.go
  certificate/certificates_test.go
  challenge/resolver/solver_manager.go
  challenge/resolver/solver_manager_test.go
  registration/registar.go
Labels: bug

#2406 Add DNS provider for Spaceship
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_spaceship.md
  docs/data/zz_cli_help.toml
  providers/dns/spaceship/internal/client.go
  providers/dns/spaceship/internal/client_test.go
  providers/dns/spaceship/internal/fixtures/error.json
  providers/dns/spaceship/internal/fixtures/get-records.json
  providers/dns/spaceship/internal/types.go
  providers/dns/spaceship/spaceship.go
  providers/dns/spaceship/spaceship.toml
  providers/dns/spaceship/spaceship_test.go
  providers/dns/zz_gen_dns_providers.go
Labels: enhancement, area/dnsprovider

#2431 feat(cli): add an option to set the private key
  certificate/certificates.go
  cmd/cmd_run.go
  docs/data/zz_cli_help.toml
Labels: enhancement, area/cli

#2434 chore: update linter
  .github/workflows/pr.yml
  .golangci.yml
Labels: enhancement, area/infrastructure

#2437 acme-dns: allow the HTTP storage server to create the CNAME
  providers/dns/acmedns/acmedns.go
  providers/dns/acmedns/internal/http_storage.go
  providers/dns/acmedns/internal/http_storage_test.go
  providers/dns/acmedns/internal/readme.md
Labels: enhancement, area/dnsprovider

#2439 acme-dns: fix file path
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/_index.md
  docs/content/dns/zz_gen_acme-dns.md
  providers/dns/acmedns/acmedns.go
  providers/dns/acmedns/acmedns.toml
  providers/dns/acmedns/acmedns_test.go
Labels: bug, area/dnsprovider

#2443 acme-dns: continue the process when the CNAME is handled by the storage
  providers/dns/acmedns/acmedns.go
Labels: bug, area/dnsprovider

#2445 acme-dns: use new registred account
  providers/dns/acmedns/acmedns.go
  providers/dns/acmedns/acmedns_test.go
  providers/dns/acmedns/mock_test.go
Labels: bug, area/dnsprovider

#2446 chore: use go1.23
  acme/api/order_test.go
  certcrypto/crypto_test.go
  challenge/dns01/dns_challenge_test.go
  challenge/http01/http_challenge_test.go
  challenge/resolver/solver_manager_test.go
  challenge/tlsalpn01/tls_alpn_challenge_test.go
  go.mod
  lego/client_test.go
  providers/dns/hyperone/internal/token_test.go
  providers/dns/oraclecloud/oraclecloud_test.go
  registration/registar_test.go
Labels: enhancement

#2452 fix: malformed log messages
  .golangci.yml
  cmd/cmd_renew.go
  providers/dns/cloudflare/cloudflare.go
  providers/dns/netcup/netcup.go
  providers/dns/shellrent/shellrent.go
Labels: bug, area/cli, area/log

#2316 Add DNS provider for BookMyName
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_bookmyname.md
  docs/data/zz_cli_help.toml
  providers/dns/bookmyname/bookmyname.go
  providers/dns/bookmyname/bookmyname.toml
  providers/dns/bookmyname/bookmyname_test.go
  providers/dns/bookmyname/internal/client.go
  providers/dns/bookmyname/internal/client_test.go
  providers/dns/bookmyname/internal/fixtures/add_success.txt
  providers/dns/bookmyname/internal/fixtures/error.txt
  providers/dns/bookmyname/internal/fixtures/remove_success.txt
  providers/dns/bookmyname/internal/types.go
  providers/dns/zz_gen_dns_providers.go
Labels: enhancement, area/dnsprovider

#2455 Add DNS provider for Metaregistrar
  README.md
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_metaregistrar.md
  docs/data/zz_cli_help.toml
  providers/dns/metaregistrar/internal/client.go
  providers/dns/metaregistrar/internal/client_test.go
  providers/dns/metaregistrar/internal/fixtures/error-response.json
  providers/dns/metaregistrar/internal/fixtures/error.json
  providers/dns/metaregistrar/internal/fixtures/update-dns-zone.json
  providers/dns/metaregistrar/internal/types.go
  providers/dns/metaregistrar/metaregistrar.go
  providers/dns/metaregistrar/metaregistrar.toml
  providers/dns/metaregistrar/metaregistrar_test.go
  providers/dns/zz_gen_dns_providers.go
Labels: enhancement, area/dnsprovider

#2458 feat: add INFOBLOX_CA_CERTIFICATE option
  cmd/zz_gen_cmd_dnshelp.go
  docs/content/dns/zz_gen_infoblox.md
  providers/dns/infoblox/infoblox.go
  providers/dns/infoblox/infoblox.toml
Labels: enhancement, area/dnsprovider

#2459 infoblox: update API client to v2
  go.mod
  go.sum
  providers/dns/infoblox/infoblox.go
Labels: area/dnsprovider
